#!/usr/bin/env python3
"""
Free AI agent that builds things in Blender.

Connects to the "AI Agent Bridge" (addon.py or bridge_standalone.py) running
inside Blender and drives it with Python code generated by an LLM.

100% free by default: Ollama on your own computer (no API key, no account,
works offline). Free hosted options (Groq, Google Gemini) are built in, and
the agent automatically falls back between providers. With a vision-capable
model the agent can RENDER its work, LOOK at the image, and fix visual
mistakes itself.

Quick start:
    1. Start the bridge in Blender:
         - install+enable addon.py and click "Start AI Agent Server", OR
         - launch:  blender --python bridge_standalone.py
    2. Install Ollama from https://ollama.com, then:
         ollama pull qwen2.5-coder:7b
    3. python agent.py "build a red sports car on a road"

Vision (agent sees its own renders):
    ollama pull llama3.2-vision:11b     # then agent.py --vision ...

Standard library only - no pip installs.
"""

import argparse
import base64
import datetime
import json
import os
import re
import shutil
import socket
import sys
import time
import traceback
import urllib.error
import urllib.request

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9876
MAX_OUTPUT_CHARS = 6000

# Output (renders / saved .blend / exports) lands here by default.
DEFAULT_OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")

# Free LLM providers, all speaking the OpenAI-compatible /chat/completions API.
PROVIDERS = {
    "ollama": {
        "base_url": "http://localhost:11434/v1",
        "model": "qwen2.5-coder:7b",
        "vision_model": "llama3.2-vision:11b",
        "api_key": "ollama",  # ignored by Ollama, required by the API shape
        "hint": "Install Ollama from https://ollama.com and run: ollama pull qwen2.5-coder:7b",
    },
    "groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "model": "llama-3.3-70b-versatile",
        "vision_model": "meta-llama/llama-4-scout-17b-16e-instruct",
        "key_env": "GROQ_API_KEY",
        "hint": "Get a free key at https://console.groq.com/keys then set GROQ_API_KEY",
    },
    "gemini": {
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "model": "gemini-2.0-flash",
        "vision_model": "gemini-2.0-flash",  # same model understands images
        "key_env": "GEMINI_API_KEY",
        "hint": "Get a free key at https://aistudio.google.com/apikey then set GEMINI_API_KEY",
    },
    "openai": {
        "base_url": "https://api.openai.com/v1",
        "model": "gpt-4o-mini",
        "vision_model": "gpt-4o-mini",
        "key_env": "OPENAI_API_KEY",
        "hint": "Set OPENAI_API_KEY (this provider is not free, listed for convenience)",
    },
}

SYSTEM_PROMPT = """You are BlenderBot, an AI agent that builds 3D scenes in a \
LIVE Blender session by writing Python code with the `bpy` API.

HOW YOU WORK
- You have tools. Use them. Do not just describe what you would do - do it.
- ALWAYS start with get_scene_info to see what is already in the scene.
- Build incrementally: geometry first, then materials, then lighting and a \
camera, then verify. Use print() to inspect things - your stdout is returned.
- The Python namespace PERSISTS between execute_blender_code calls: variables \
defined in one call are available later.
- If a call errors, read the traceback carefully and fix it in your next call. \
Never repeat the same failing code. If your scene gets into a mess, call \
undo_blender to roll back and try again.
- Make sensible assumptions instead of asking questions. Name objects and \
materials descriptively. Keep geometry clean.
- Always finish with:
    1. save_blend to write the scene to disk (use the suggested directory),
    2. render_and_inspect (or render_preview) to visually verify,
    3. task_complete with a short summary of what was built.

VISION FEEDBACK (when render_and_inspect is available)
- After major milestones, call render_and_inspect: it renders the scene and \
returns the IMAGE to you plus a data URI you can read. Look at it critically: \
is anything floating, intersecting badly, misaligned, missing, the wrong \
color, badly framed, or too dark? If so, fix it with code and inspect again. \
Do not trust that the scene looks right just because the code ran.

bpy CHEAT SHEET (prefer the data API over bpy.ops where possible)

Clear the whole scene:
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for block in (bpy.data.meshes, bpy.data.curves, bpy.data.materials,
                  bpy.data.cameras, bpy.data.lights):
        for item in list(block):
            block.remove(item)

Create primitives:
    bpy.ops.mesh.primitive_cube_add(size=2, location=(0, 0, 1))
    bpy.ops.mesh.primitive_uv_sphere_add(radius=1, location=(0, 0, 2))
    bpy.ops.mesh.primitive_cylinder_add(radius=0.5, depth=2, location=(2, 0, 1))
    bpy.ops.mesh.primitive_plane_add(size=20, location=(0, 0, 0))
    bpy.ops.mesh.primitive_cone_add(vertices=4, radius1=2, depth=1.5)
    bpy.ops.mesh.primitive_torus_add(major_radius=1, minor_radius=0.25)
    obj = bpy.context.active_object
    obj.name = "Desk"

Transforms:
    obj.location = (1, 2, 0.5)
    obj.rotation_euler = (0, 0, 0.785)   # radians
    obj.scale = (2, 1, 0.5)

Materials:
    mat = bpy.data.materials.new("Wood")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (0.55, 0.35, 0.15, 1)  # RGBA, 0-1
    bsdf.inputs["Roughness"].default_value = 0.6
    bsdf.inputs["Metallic"].default_value = 0.0
    obj.data.materials.append(mat)

Modifiers:
    bevel = obj.modifiers.new("Bevel", 'BEVEL'); bevel.width = 0.05
    sub = obj.modifiers.new("Subsurf", 'SUBSURF'); sub.levels = 2

Point a camera/light at a target:
    from mathutils import Vector
    def point_at(obj, target):
        d = Vector(target) - obj.location
        obj.rotation_euler = d.to_track_quat('-Z', 'Y').to_euler()
    bpy.ops.object.camera_add(location=(7, -7, 5))
    cam = bpy.context.active_object
    bpy.context.scene.camera = cam
    point_at(cam, (0, 0, 1))

Lighting and world:
    bpy.ops.object.light_add(type='SUN', location=(4, -4, 8))
    bpy.context.active_object.data.energy = 3.0
    world = bpy.context.scene.world
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.05, 0.08, 0.12, 1)
    bg.inputs["Strength"].default_value = 0.3

Render engine (set defensively - names differ across Blender versions):
    for engine in ('BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE'):
        try:
            bpy.context.scene.render.engine = engine
            break
        except TypeError:
            continue

Animation:
    scene.frame_start = 1; scene.frame_end = 60
    obj.location = (0, 0, 0); obj.keyframe_insert("location", frame=1)
    obj.location = (0, 0, 3); obj.keyframe_insert("location", frame=60)

Saving / exporting (dedicated tools also exist):
    bpy.ops.wm.save_as_mainfile(filepath="/absolute/path/scene.blend")

RULES
- Do not use blocking code (time.sleep, infinite loops, file dialogs).
- Never rely on a specific UI context for bpy.ops; create materials via \
bpy.data and operate on bpy.context.active_object right after an add operator.
- Write complete, runnable code in every execute_blender_code call.
- Keep each code call focused (one logical change) so errors are easy to fix.
"""

TOOL_DEFS = {
    "get_scene_info": {
        "description": "Get information about the current Blender scene: all "
                       "objects (name, type, transform, materials), materials, "
                       "collections, camera and render settings. Call this first.",
        "parameters": {"type": "object", "properties": {}},
    },
    "execute_blender_code": {
        "description": "Execute Python code inside the live Blender process "
                       "using the bpy API. The global namespace persists "
                       "between calls. Captured stdout (print output) and any "
                       "error traceback are returned.",
        "parameters": {
            "type": "object",
            "properties": {
                "code": {"type": "string",
                         "description": "Python code using bpy to run in Blender."}
            },
            "required": ["code"],
        },
    },
    "render_and_inspect": {
        "description": "Render the scene from the active camera to a PNG and "
                       "ANALYZE IT YOURSELF (the image is attached to the "
                       "resulting message). Use this to visually verify your "
                       "work and spot mistakes. A camera must exist.",
        "parameters": {
            "type": "object",
            "properties": {
                "note": {"type": "string",
                         "description": "Optional: what you are checking for."}
            },
        },
    },
    "render_preview": {
        "description": "Render the scene to a PNG file for the USER to open "
                       "(you do not see the image). Use when vision is "
                       "unavailable or the user explicitly asks for a render.",
        "parameters": {
            "type": "object",
            "properties": {
                "filepath": {"type": "string",
                             "description": "Optional absolute .png output path."}
            },
        },
    },
    "save_blend": {
        "description": "Save the Blender project as a .blend file so the user "
                       "can open it later.",
        "parameters": {
            "type": "object",
            "properties": {
                "filepath": {"type": "string",
                             "description": "Absolute path ending in .blend. "
                                            "A sensible default is provided if omitted."}
            },
        },
    },
    "export_model": {
        "description": "Export the scene mesh for external use (3D printing, "
                       "game engines, etc.).",
        "parameters": {
            "type": "object",
            "properties": {
                "format": {"type": "string", "enum": ["GLB", "GLTF", "STL", "FBX", "OBJ"],
                           "description": "GLB/FBX for games, STL for 3D printing."},
                "filepath": {"type": "string",
                             "description": "Absolute output path (extension added if needed)."}
            },
            "required": ["format"],
        },
    },
    "undo_blender": {
        "description": "Undo the last Blender change (one agent step). Use to "
                       "roll back a mistake instead of manually deleting objects.",
        "parameters": {"type": "object", "properties": {}},
    },
    "task_complete": {
        "description": "Call when the user's request has been fully built and "
                       "verified. Stops the agent loop.",
        "parameters": {
            "type": "object",
            "properties": {
                "summary": {"type": "string",
                            "description": "Short summary of what was built."}
            },
            "required": ["summary"],
        },
    },
}

# Tools exposed when the model cannot see images.
TEXT_TOOL_ORDER = ["get_scene_info", "execute_blender_code", "render_preview",
                   "save_blend", "export_model", "undo_blender", "task_complete"]
# Tools exposed to a vision-capable model.
VISION_TOOL_ORDER = ["get_scene_info", "execute_blender_code",
                     "render_and_inspect", "render_preview",
                     "save_blend", "export_model", "undo_blender", "task_complete"]


def build_tools(vision):
    order = VISION_TOOL_ORDER if vision else TEXT_TOOL_ORDER
    return [{"type": "function",
             "function": {"name": name,
                          "description": TOOL_DEFS[name]["description"],
                          "parameters": TOOL_DEFS[name]["parameters"]}}
            for name in order]


# --------------------------------------------------------------------------
# Blender bridge client
# --------------------------------------------------------------------------

class BlenderBridge:
    """JSON-lines client for the addon.py socket server."""

    def __init__(self, host=DEFAULT_HOST, port=DEFAULT_PORT, timeout=300):
        self.host = host
        self.port = port
        self.sock = socket.create_connection((host, port), timeout=10)
        self.sock.settimeout(timeout)
        self._buf = b""
        self._id = 0

    def call(self, cmd, **args):
        self._id += 1
        request = {"id": self._id, "cmd": cmd, "args": args}
        self.sock.sendall((json.dumps(request) + "\n").encode("utf-8"))
        while True:
            reply = json.loads(self._readline().decode("utf-8"))
            if reply.get("id") == self._id:
                return reply

    def _readline(self):
        while b"\n" not in self._buf:
            chunk = self.sock.recv(65536)
            if not chunk:
                raise ConnectionError("Blender closed the connection")
            self._buf += chunk
        line, self._buf = self._buf.split(b"\n", 1)
        return line

    def close(self):
        try:
            self.sock.close()
        except OSError:
            pass


# --------------------------------------------------------------------------
# LLM client (OpenAI-compatible; works with Ollama, Groq, Gemini, OpenAI)
# --------------------------------------------------------------------------

def detect_provider(explicit):
    """Auto-pick a provider from available API keys / a running Ollama."""
    if explicit:
        return explicit
    if os.environ.get("GROQ_API_KEY"):
        return "groq"
    if os.environ.get("GEMINI_API_KEY"):
        return "gemini"
    if os.environ.get("OPENAI_API_KEY"):
        return "openai"
    return "ollama"


class LLMClient:
    def __init__(self, provider="ollama", model=None, base_url=None,
                 api_key=None, vision=False, temperature=0.2, log=print):
        self.provider = provider
        cfg = PROVIDERS[provider]
        self.base_url = (base_url or cfg["base_url"]).rstrip("/")
        self.model = model or (cfg.get("vision_model") if vision else None) or cfg["model"]
        key = api_key
        if not key and cfg.get("key_env"):
            key = os.environ.get(cfg["key_env"], "")
        self.api_key = key or cfg.get("api_key", "")
        self.vision = vision
        self.temperature = temperature
        self.hint = cfg.get("hint", "")
        self.log = log

    def chat(self, messages, tools=None, retries=3):
        payload = {"model": self.model, "messages": messages,
                   "temperature": self.temperature}
        if tools:
            payload["tools"] = tools
        data = json.dumps(payload).encode("utf-8")

        for attempt in range(retries):
            req = urllib.request.Request(
                self.base_url + "/chat/completions",
                data=data,
                headers={"Content-Type": "application/json",
                         "Authorization": "Bearer " + self.api_key},
            )
            try:
                with urllib.request.urlopen(req, timeout=600) as resp:
                    body = json.loads(resp.read().decode("utf-8"))
                return body["choices"][0]["message"]
            except urllib.error.HTTPError as exc:
                detail = exc.read().decode("utf-8", "replace")[:600]
                if exc.code in (429, 500, 502, 503) and attempt < retries - 1:
                    wait = 2 ** attempt
                    self.log("[LLM busy (%d); retrying in %ds]" % (exc.code, wait))
                    time.sleep(wait)
                    continue
                raise RuntimeError(
                    "LLM API HTTP %s for %s (%s): %s\nHint: %s"
                    % (exc.code, self.base_url, self.model, detail, self.hint))
            except urllib.error.URLError as exc:
                if attempt < retries - 1:
                    wait = 2 ** attempt
                    self.log("[cannot reach LLM (%s); retrying in %ds]" % (exc.reason, wait))
                    time.sleep(wait)
                    continue
                raise RuntimeError("Cannot reach the LLM at %s: %s\nHint: %s"
                                   % (self.base_url, exc.reason, self.hint))


def chat_with_fallback(llms, messages, tools, log=print):
    """Try LLM clients in order; return (message, index_used)."""
    last = None
    for i, llm in enumerate(llms):
        try:
            return llm.chat(messages, tools), i
        except RuntimeError as exc:
            last = exc
            log("[provider '%s' failed: %s]" % (llm.provider, str(exc).splitlines()[0]))
            if i < len(llms) - 1:
                nxt = llms[i + 1]
                log("[falling back to '%s' (%s)]" % (nxt.provider, nxt.model))
    raise last


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def _truncate(text):
    if text is None:
        return ""
    text = str(text)
    return text if len(text) <= MAX_OUTPUT_CHARS else text[:MAX_OUTPUT_CHARS] + "\n...[truncated]"


def _repair_json(raw):
    """Best-effort fix for model-emitted tool arguments that aren't valid JSON."""
    if isinstance(raw, dict):
        return raw
    if not raw:
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    # Find the outermost { ... } block.
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    candidate = match.group(0) if match else raw
    candidate = candidate.replace("\n", " ")
    # Common slip: Python-style True/False/None or single quotes around keys.
    try:
        return json.loads(candidate)
    except json.JSONDecodeError:
        pass
    # Extract a string value for known scalar keys as a last resort
    # (handles trailing commas, single-quoted keys, trailing prose, ...).
    # Try double-quoted values first, then single-quoted.
    for key in ("code", "summary", "filepath", "format", "note"):
        m = re.search(r"['\"]?%s['\"]?\s*:\s*\"(.*)\"\s*[,})\]]*$" % key,
                      candidate, re.DOTALL)
        if not m:
            m = re.search(r"['\"]?%s['\"]?\s*:\s*'(.*)'\s*[,})\]]*$" % key,
                          candidate, re.DOTALL)
        if m:
            value = m.group(1)
            try:
                return {key: json.loads('"%s"' % value)}
            except json.JSONDecodeError:
                return {key: value}
    return {}


def _ensure_out_dir():
    os.makedirs(DEFAULT_OUT_DIR, exist_ok=True)
    return DEFAULT_OUT_DIR


def _timestamped(prefix, ext):
    _ensure_out_dir()
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(DEFAULT_OUT_DIR, "%s_%s.%s" % (prefix, stamp, ext))


def _read_image_data_uri(path):
    with open(path, "rb") as fh:
        b64 = base64.b64encode(fh.read()).decode("ascii")
    return "data:image/png;base64," + b64


def encode_reference_image(path):
    """Load a user-provided reference image as a data URI."""
    ext = os.path.splitext(path)[1].lower().lstrip(".")
    mime = {"jpg": "jpeg", "jpeg": "jpeg", "png": "png",
            "webp": "webp", "gif": "gif"}.get(ext, "png")
    with open(path, "rb") as fh:
        b64 = base64.b64encode(fh.read()).decode("ascii")
    return "data:image/%s;base64,%s" % (mime, b64)


# --------------------------------------------------------------------------
# Tool execution
# --------------------------------------------------------------------------

def _ask_approval(code, log):
    print("\n--- Agent wants to run this Blender code ---")
    print(code)
    print("-------------------------------------------")
    try:
        answer = input("Approve? [Enter=run, s=skip, q=quit] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return "run"
    if answer in ("q", "quit"):
        return "quit"
    if answer in ("s", "skip", "n", "no"):
        return "skip"
    return "run"


def dispatch_tool(name, args, bridge, vision=False, log=print, approve=False):
    """Run one tool call against Blender.

    Returns (content_text, extra_messages):
      content_text   -> string for the ordinary tool-role reply
      extra_messages -> extra messages to append (e.g. vision images)
    """
    if name == "get_scene_info":
        reply = bridge.call("scene_info")
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error"), []
        return json.dumps(reply["result"], indent=2), []

    if name == "execute_blender_code":
        code = args.get("code", "")
        log("\n--- Blender code ---")
        for line in code.strip().splitlines():
            log("  " + line)
        log("--------------------")
        if approve:
            decision = _ask_approval(code, log)
            if decision == "quit":
                raise KeyboardInterrupt
            if decision == "skip":
                return "Skipped by the user. Try a different approach.", []
        reply = bridge.call("exec", code=code)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error"), []
        result = reply.get("result") or {}
        parts = []
        if result.get("stdout", "").strip():
            parts.append("stdout:\n" + result["stdout"].strip())
        if result.get("error"):
            parts.append("Python error (read the traceback and fix your code):\n"
                         + result["error"])
        if not parts:
            return "Code executed successfully with no output.", []
        return _truncate("\n\n".join(parts)), []

    if name in ("render_preview", "render_and_inspect"):
        path = args.get("filepath") or _timestamped("render", "png")
        note = args.get("note", "")
        log("\n[rendering preview -> %s ...]" % path)
        reply = bridge.call("render", filepath=path)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error"), []
        result = reply.get("result") or {}
        if result.get("error"):
            return "Render failed:\n" + result["error"], []
        out_path = result.get("filepath", path)
        log("[render saved: %s]" % out_path)

        text = ("Render saved to: %s%s"
                % (out_path, (" Note from you: " + note) if note else ""))
        extra = []
        if name == "render_and_inspect":
            if not vision:
                text += (" (Image attached below for analysis. If you cannot "
                         "see images, use render_preview instead.)")
            try:
                uri = _read_image_data_uri(out_path)
                extra.append({
                    "role": "user",
                    "content": [
                        {"type": "text",
                         "text": "This is the render of your current Blender "
                                 "scene. Inspect it carefully for problems "
                                 "(floating/intersecting objects, wrong colors, "
                                 "bad camera framing, missing parts) and fix any "
                                 "issues you see with execute_blender_code."
                                 + ((" Focus: " + note) if note else "")},
                        {"type": "image_url", "image_url": {"url": uri}},
                    ],
                })
            except Exception as exc:
                text += "\n(Warning: could not attach image: %s)" % exc
        return text, extra

    if name == "save_blend":
        path = args.get("filepath") or _timestamped("scene", "blend")
        if not path.lower().endswith(".blend"):
            path += ".blend"
        log("[saving .blend -> %s]" % path)
        reply = bridge.call("save", filepath=path)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error"), []
        result = reply.get("result") or {}
        if result.get("error"):
            return "Save failed:\n" + result["error"], []
        return "Saved Blender file to: %s" % result.get("filepath", path), []

    if name == "export_model":
        fmt = (args.get("format") or "").upper()
        path = args.get("filepath") or _timestamped("export", fmt.lower())
        log("[exporting %s -> %s]" % (fmt, path))
        reply = bridge.call("export", filepath=path, format=fmt)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error"), []
        result = reply.get("result") or {}
        if result.get("error"):
            return "Export failed:\n" + result["error"], []
        return "Exported %s to: %s" % (fmt, result.get("filepath", path)), []

    if name == "undo_blender":
        reply = bridge.call("undo")
        result = reply.get("result") or {}
        if result.get("error") or not reply.get("ok"):
            return "Undo failed: %s" % (result.get("error") or reply.get("error")), []
        return "Undid the last Blender step.", []

    if name == "task_complete":
        return None, []

    return "ERROR: unknown tool %r" % name, []


# --------------------------------------------------------------------------
# Agent loop
# --------------------------------------------------------------------------

def run_task(task, bridge, llms, vision=False, max_iters=30, approve=False,
             reference_image=None, log=print):
    """Run one user request. `llms` is a list of LLMClient (fallback chain)."""
    if isinstance(llms, LLMClient):
        llms = [llms]
    tools = build_tools(vision)

    user_content = task
    if reference_image:
        log("[attaching reference image: %s]" % reference_image)
        user_content = [
            {"type": "text",
             "text": task + "\n\n(The attached image is a reference for what "
                            "I want. Build something based on it.)"},
            {"type": "image_url",
             "image_url": {"url": encode_reference_image(reference_image)}},
        ]

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]

    for step in range(1, max_iters + 1):
        log("\n[step %d] thinking..." % step)
        message, used = chat_with_fallback(llms, messages, tools, log=log)
        messages.append(message)

        tool_calls = message.get("tool_calls") or []
        content = (message.get("content") or "").strip()
        if content:
            log("AI: " + content)

        if not tool_calls:
            log("\n(The model finished without calling task_complete.)")
            return content or "Task finished."

        done_summary = None
        for call in tool_calls:
            fn = call.get("function", {})
            name = fn.get("name", "")
            args = _repair_json(fn.get("arguments") or "{}")

            if name == "task_complete":
                done_summary = args.get("summary", "Task complete.")
                messages.append({"role": "tool", "tool_call_id": call.get("id", "0"),
                                 "content": "Task marked complete."})
                continue

            try:
                tool_text, extra = dispatch_tool(
                    name, args, bridge, vision=vision, log=log, approve=approve)
            except KeyboardInterrupt:
                return "Stopped by user during approval."
            except (ConnectionError, OSError) as exc:
                raise RuntimeError(
                    "Lost connection to Blender: %s\nMake sure the bridge is "
                    "running (add-on panel > Start, or blender --python "
                    "bridge_standalone.py)." % exc)

            messages.append({"role": "tool", "tool_call_id": call.get("id", "0"),
                             "content": tool_text if tool_text is not None else "done"})
            # Vision results arrive as a follow-up user message containing the image.
            messages.extend(extra)

        if done_summary is not None:
            log("\n=== Done: %s ===" % done_summary)
            log("[files written to: %s]" % DEFAULT_OUT_DIR)
            return done_summary

    log("\n[reached max iterations (%d); stopping]" % max_iters)
    return "Stopped after %d steps." % max_iters


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def connect_with_help(host, port):
    try:
        bridge = BlenderBridge(host, port)
    except (ConnectionError, OSError) as exc:
        print("Could not connect to Blender at %s:%d (%s)." % (host, port, exc))
        print("Start the bridge first:\n"
              "  - Blender: N-panel > 'AI Agent' tab > 'Start AI Agent Server', or\n"
              "  - run: blender --python bridge_standalone.py")
        sys.exit(1)
    reply = bridge.call("ping")
    if reply.get("ok"):
        info = reply["result"]
        print("Connected to Blender %s (scene: %s)."
              % (info.get("blender"), info.get("scene")))
    return bridge


def build_llm_chain(args):
    """Construct primary + fallback LLM clients."""
    primary = detect_provider(args.provider)
    chain_names = [primary]
    if args.fallback and not args.no_fallback:
        for name in ("ollama", "groq", "gemini"):
            if name != primary and name not in chain_names:
                chain_names.append(name)

    llms = []
    for name in chain_names:
        cfg = PROVIDERS[name]
        if cfg.get("key_env") and not os.environ.get(cfg["key_env"]) and not args.api_key:
            continue  # provider has no key configured; skip silently
        model = args.model if name == primary else None
        base_url = args.base_url if name == primary else None
        llms.append(LLMClient(provider=name, model=model, base_url=base_url,
                              api_key=args.api_key if name == primary else None,
                              vision=args.vision))
    if not llms:
        llms = [LLMClient(provider=primary, vision=args.vision)]
    return llms


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Free AI agent that builds things in Blender.")
    parser.add_argument("task", nargs="?",
                        help="What you want built, e.g. \"a small windmill\". "
                             "Omit for interactive chat mode.")
    parser.add_argument("--provider", default=os.environ.get("LLM_PROVIDER"),
                        choices=sorted(PROVIDERS.keys()),
                        help="LLM provider (default: auto-detect; else ollama).")
    parser.add_argument("--model", default=os.environ.get("LLM_MODEL"),
                        help="Override the model name.")
    parser.add_argument("--base-url", default=os.environ.get("LLM_BASE_URL"),
                        help="Override the API base URL (OpenAI-compatible server).")
    parser.add_argument("--api-key", default=None, help="API key override.")
    parser.add_argument("--vision", action="store_true",
                        help="Enable vision: the agent renders and looks at its "
                             "work (use a vision model, e.g. ollama pull "
                             "llama3.2-vision:11b).")
    parser.add_argument("--no-fallback", action="store_true",
                        help="Do not fall back to other free providers on error.")
    parser.add_argument("--approve", action="store_true",
                        help="Ask before running each piece of Blender code.")
    parser.add_argument("--image", metavar="PATH",
                        help="Reference image the agent should build from (requires --vision).")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--max-iters", type=int, default=30)
    parser.add_argument("--exec", metavar="FILE",
                        help="Skip the LLM: run a .py file inside Blender.")
    args = parser.parse_args(argv)

    if args.image and not args.vision:
        args.vision = True  # reference images require a vision-capable model

    bridge = connect_with_help(args.host, args.port)

    if args.exec:
        with open(args.exec, "r", encoding="utf-8") as fh:
            code = fh.read()
        reply = bridge.call("exec", code=code)
        result = reply.get("result") or {}
        if result.get("stdout"):
            print(result["stdout"], end="")
        if result.get("error"):
            print(result["error"], file=sys.stderr)
            sys.exit(1)
        return

    llms = build_llm_chain(args)
    print("LLM chain: %s | vision: %s | approve: %s"
          % (" -> ".join("%s(%s)" % (l.provider, l.model) for l in llms),
             "on" if args.vision else "off",
             "on" if args.approve else "off"))
    if args.vision:
        print("Vision enabled - the agent will render and inspect its work.")

    def loop(task_text, ref_image=None):
        return run_task(task_text, bridge, llms, vision=args.vision,
                        max_iters=args.max_iters, approve=args.approve,
                        reference_image=ref_image)

    try:
        if args.task:
            loop(args.task, args.image)
        else:
            print("\nInteractive mode. Describe what you want built. Commands: "
                  "/scene, /undo, /render, /save, /quit\n")
            while True:
                try:
                    task_text = input("you > ").strip()
                except (EOFError, KeyboardInterrupt):
                    print()
                    break
                if not task_text:
                    continue
                if task_text in ("/quit", "/exit"):
                    break
                if task_text == "/scene":
                    print(json.dumps(bridge.call("scene_info").get("result", {}), indent=2))
                    continue
                if task_text == "/undo":
                    print(bridge.call("undo"))
                    continue
                if task_text == "/render":
                    print(bridge.call("render", filepath=_timestamped("render", "png")))
                    continue
                if task_text == "/save":
                    print(bridge.call("save", filepath=_timestamped("scene", "blend")))
                    continue
                try:
                    loop(task_text)
                except RuntimeError as exc:
                    print("\n[agent error] %s" % exc)
    except RuntimeError as exc:
        print("\n[agent error] %s" % exc)
        if "11434" in str(exc) or "ollama" in str(exc).lower():
            print("\nOllama quick start:\n"
                  "  1. Download Ollama: https://ollama.com\n"
                  "  2. ollama pull qwen2.5-coder:7b"
                  + ("\n     (vision) ollama pull llama3.2-vision:11b" if args.vision else "")
                  + "\n  3. Make sure Ollama is running, then try again.")
        sys.exit(1)
    finally:
        bridge.close()


if __name__ == "__main__":
    main()
