#!/usr/bin/env python3
"""
Free AI agent that builds things in Blender.

This script connects to the "AI Agent Bridge" add-on running inside Blender
(addon.py) and drives it with Python code generated by an LLM.

It is 100% free by default: it uses Ollama running on your own computer,
so there is no API key, no account and no cost. Free hosted alternatives
(Groq, Google Gemini) are also supported.

Quick start:
    1. In Blender: install+enable addon.py, press N in the 3D viewport,
       open the "AI Agent" tab, click "Start AI Agent Server".
    2. Install Ollama from https://ollama.com and run:  ollama pull qwen2.5-coder:7b
    3. Run:   python agent.py "build a red sports car on a road"

No pip installs required - standard library only.
"""

import argparse
import json
import os
import shlex
import socket
import sys
import traceback
import urllib.error
import urllib.request

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9876
MAX_OUTPUT_CHARS = 6000  # truncate tool output sent back to the LLM

# Free LLM providers. All speak the OpenAI-compatible /chat/completions API.
PROVIDERS = {
    "ollama": {
        "base_url": "http://localhost:11434/v1",
        "model": "qwen2.5-coder:7b",
        "api_key": "ollama",  # ignored by Ollama, required by the API shape
        "hint": "Install Ollama from https://ollama.com and run: ollama pull qwen2.5-coder:7b",
    },
    "groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "model": "llama-3.3-70b-versatile",
        "key_env": "GROQ_API_KEY",
        "hint": "Get a free key at https://console.groq.com/keys then set GROQ_API_KEY",
    },
    "gemini": {
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "model": "gemini-2.0-flash",
        "key_env": "GEMINI_API_KEY",
        "hint": "Get a free key at https://aistudio.google.com/apikey then set GEMINI_API_KEY",
    },
    "openai": {
        "base_url": "https://api.openai.com/v1",
        "model": "gpt-4o-mini",
        "key_env": "OPENAI_API_KEY",
        "hint": "Set OPENAI_API_KEY (this provider is not free, listed for convenience)",
    },
}

SYSTEM_PROMPT = """You are BlenderBot, an AI agent that builds 3D scenes in a \
LIVE Blender session by writing Python code with the `bpy` API.

HOW YOU WORK
- You have tools. Use them. Do not just describe what you would do - do it.
- ALWAYS start with get_scene_info to see what is already in the scene.
- Build the result incrementally: create geometry, then materials, then \
lighting and a camera, then verify. Use print() to inspect things - your \
stdout is returned to you.
- The Python namespace PERSISTS between execute_blender_code calls: variables \
you define in one call are available in later calls.
- If a call errors, read the traceback carefully and fix it in your next call. \
Never repeat the same failing code.
- Make sensible assumptions instead of asking questions. Keep geometry clean \
and reasonably low-poly. Name objects and materials descriptively.
- When the scene is finished, call task_complete with a short summary.

bpy CHEAT SHEET (prefer the data API over bpy.ops where possible)

Clear the whole scene:
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for block in (bpy.data.meshes, bpy.data.curves, bpy.data.materials,
                  bpy.data.cameras, bpy.data.lights):
        for item in list(block):
            block.remove(item)

Create primitives (ops are fine for these):
    bpy.ops.mesh.primitive_cube_add(size=2, location=(0, 0, 1))
    bpy.ops.mesh.primitive_uv_sphere_add(radius=1, location=(0, 0, 2))
    bpy.ops.mesh.primitive_cylinder_add(radius=0.5, depth=2, location=(2, 0, 1))
    bpy.ops.mesh.primitive_plane_add(size=20, location=(0, 0, 0))
    bpy.ops.mesh.primitive_torus_add(major_radius=1, minor_radius=0.25)
    obj = bpy.context.active_object
    obj.name = "Desk"

Join / transform:
    obj.location = (1, 2, 0.5)
    obj.rotation_euler = (0, 0, 0.785)   # radians
    obj.scale = (2, 1, 0.5)

Create and assign a material:
    mat = bpy.data.materials.new("Wood")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (0.55, 0.35, 0.15, 1)  # RGBA, 0-1
    bsdf.inputs["Roughness"].default_value = 0.6
    bsdf.inputs["Metallic"].default_value = 0.0
    obj.data.materials.append(mat)

Emission material (e.g. a screen or lamp):
    bsdf.inputs["Emission Color"].default_value = (0.2, 0.6, 1.0, 1)
    bsdf.inputs["Emission Strength"].default_value = 5.0

Modifiers:
    bevel = obj.modifiers.new("Bevel", 'BEVEL')
    bevel.width = 0.05
    bevel.segments = 3
    sub = obj.modifiers.new("Subsurf", 'SUBSURF')
    sub.levels = 2

Point a camera or light at a target:
    from mathutils import Vector
    def point_at(obj, target):
        direction = Vector(target) - obj.location
        obj.rotation_euler = direction.to_track_quat('-Z', 'Y').to_euler()
    bpy.ops.object.camera_add(location=(7, -7, 5))
    cam = bpy.context.active_object
    bpy.context.scene.camera = cam
    point_at(cam, (0, 0, 1))

Lighting and world:
    bpy.ops.object.light_add(type='SUN', location=(4, -4, 8))
    bpy.context.active_object.data.energy = 3.0
    bpy.ops.object.light_add(type='AREA', location=(0, -4, 4))
    bpy.context.active_object.data.energy = 500
    world = bpy.context.scene.world
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs["Color"].default_value = (0.05, 0.08, 0.12, 1)
    world.node_tree.nodes["Background"].inputs["Strength"].default_value = 0.3

Render settings:
    scene = bpy.context.scene
    scene.render.engine = 'BLENDER_EEVEE_NEXT'  # (use 'BLENDER_EEVEE' on Blender 3.x)
    scene.render.resolution_x = 1280
    scene.render.resolution_y = 720
    scene.render.film_transparent = False

Animation:
    scene.frame_start = 1
    scene.frame_end = 60
    obj.location = (0, 0, 0); obj.keyframe_insert("location", frame=1)
    obj.location = (0, 0, 3); obj.keyframe_insert("location", frame=60)

Save the file:
    bpy.ops.wm.save_as_mainfile(filepath="/absolute/path/scene.blend")

RULES
- Only call render_preview if the user asks for a render/image; it is slow.
- Never call bpy.ops that need a specific UI context without checking - prefer \
data API equivalents (e.g. create materials via bpy.data, not context menus).
- Do not use blocking code (time.sleep, infinite loops, file dialogs).
- Write complete, runnable code in every execute_blender_code call.
"""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_scene_info",
            "description": "Get information about the current Blender scene: "
                           "all objects (name, type, transform, materials), "
                           "materials, collections, camera and render settings. "
                           "Call this first.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "execute_blender_code",
            "description": "Execute Python code inside the live Blender process "
                           "using the bpy API. The global namespace persists "
                           "between calls. Captured stdout (print output) and any "
                           "error traceback are returned.",
            "parameters": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string",
                        "description": "Python code using bpy to run in Blender.",
                    }
                },
                "required": ["code"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "render_preview",
            "description": "Render the scene from the active camera to a PNG file "
                                           "and return its filepath (for the user to open).",
            "parameters": {
                "type": "object",
                "properties": {
                    "filepath": {
                        "type": "string",
                        "description": "Optional absolute output .png path. "
                                       "A temp file is used if omitted.",
                    }
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "task_complete",
            "description": "Call when the user's request has been fully built. "
                                           "Stops the agent loop.",
            "parameters": {
                "type": "object",
                "properties": {
                    "summary": {
                        "type": "string",
                        "description": "Short summary of what was built.",
                    }
                },
                "required": ["summary"],
            },
        },
    },
]


# --------------------------------------------------------------------------
# Blender bridge client
# --------------------------------------------------------------------------

class BlenderBridge:
    """JSON-lines client for the addon.py socket server."""

    def __init__(self, host=DEFAULT_HOST, port=DEFAULT_PORT, timeout=120):
        self.host = host
        self.port = port
        self.sock = socket.create_connection((host, port), timeout=10)
        self.sock.settimeout(timeout)
        self._buf = b""
        self._id = 0

    def call(self, cmd, **args):
        self._id += 1
        request = {"id": self._id, "cmd": cmd, "args": args}
        self.sock.sendall((json.dumps(request) + "\n").encode("utf-8"))
        while True:
            line = self._readline()
            reply = json.loads(line.decode("utf-8"))
            if reply.get("id") == self._id:
                return reply

    def _readline(self):
        while b"\n" not in self._buf:
            chunk = self.sock.recv(65536)
            if not chunk:
                raise ConnectionError("Blender closed the connection")
            self._buf += chunk
        line, self._buf = self._buf.split(b"\n", 1)
        return line

    def close(self):
        try:
            self.sock.close()
        except OSError:
            pass


# --------------------------------------------------------------------------
# LLM client (OpenAI-compatible; works with Ollama, Groq, Gemini, OpenAI)
# --------------------------------------------------------------------------

class LLMClient:
    def __init__(self, provider="ollama", model=None, base_url=None,
                 api_key=None, temperature=0.2):
        if provider not in PROVIDERS:
            raise ValueError("Unknown provider %r. Choose from: %s"
                             % (provider, ", ".join(PROVIDERS)))
        cfg = PROVIDERS[provider]
        self.provider = provider
        self.base_url = (base_url or cfg["base_url"]).rstrip("/")
        self.model = model or cfg["model"]
        key = api_key
        if not key and cfg.get("key_env"):
            key = os.environ.get(cfg["key_env"], "")
        self.api_key = key or cfg.get("api_key", "")
        self.temperature = temperature
        self.hint = cfg.get("hint", "")

    def chat(self, messages, tools=None):
        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": self.temperature,
        }
        if tools:
            payload["tools"] = tools
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.base_url + "/chat/completions",
            data=data,
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer " + self.api_key,
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=600) as resp:
                body = json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")[:800]
            raise RuntimeError(
                "LLM API returned HTTP %s for %s (%s). Response: %s\nHint: %s"
                % (exc.code, self.base_url, self.model, detail, self.hint))
        except urllib.error.URLError as exc:
            raise RuntimeError(
                "Cannot reach the LLM at %s: %s\nHint: %s"
                % (self.base_url, exc.reason, self.hint))
        return body["choices"][0]["message"]


# --------------------------------------------------------------------------
# Agent loop
# --------------------------------------------------------------------------

def _truncate(text):
    if text is None:
        return ""
    text = str(text)
    if len(text) > MAX_OUTPUT_CHARS:
        return text[:MAX_OUTPUT_CHARS] + "\n...[truncated]"
    return text


def _dispatch_tool(name, args, bridge, log=print):
    """Run one tool call against Blender; return string content for the LLM."""
    if name == "get_scene_info":
        reply = bridge.call("scene_info")
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error")
        return json.dumps(reply["result"], indent=2)

    if name == "execute_blender_code":
        code = args.get("code", "")
        log("\n--- Blender code ---")
        for line in code.strip().splitlines():
            log("  " + line)
        log("--------------------")
        reply = bridge.call("exec", code=code)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error")
        result = reply.get("result") or {}
        parts = []
        if result.get("stdout", "").strip():
            parts.append("stdout:\n" + result["stdout"].strip())
        if result.get("error"):
            parts.append("Python error (fix your code):\n" + result["error"])
        if not parts:
            return "Code executed successfully with no output."
        return _truncate("\n\n".join(parts))

    if name == "render_preview":
        log("\n[rendering preview...]")
        kwargs = {}
        if args.get("filepath"):
            kwargs["filepath"] = args["filepath"]
        reply = bridge.call("render", **kwargs)
        if not reply.get("ok"):
            return "ERROR: " + reply.get("error", "unknown error")
        result = reply.get("result") or {}
        if result.get("error"):
            return "Render failed:\n" + result["error"]
        log("[render saved to: %s]" % result.get("filepath"))
        return "Render saved to: %s (tell the user to open this file)." % result.get("filepath")

    if name == "task_complete":
        return None  # handled by caller

    return "ERROR: unknown tool %r" % name


def run_task(task, bridge, llm, max_iters=30, log=print):
    """Run one user request to completion. Returns the completion summary."""
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": task},
    ]

    for step in range(1, max_iters + 1):
        log("\n[step %d] thinking..." % step)
        message = llm.chat(messages, TOOLS)
        messages.append(message)

        tool_calls = message.get("tool_calls") or []
        content = (message.get("content") or "").strip()
        if content:
            log("AI: " + content)

        if not tool_calls:
            log("\n(The model finished without calling task_complete.)")
            return content or "Task finished."

        done_summary = None
        for call in tool_calls:
            fn = call.get("function", {})
            name = fn.get("name", "")
            raw_args = fn.get("arguments") or "{}"
            try:
                args = json.loads(raw_args) if isinstance(raw_args, str) else raw_args
            except json.JSONDecodeError:
                args = {}

            if name == "task_complete":
                done_summary = args.get("summary", "Task complete.")
                tool_content = "Task marked complete."
            else:
                try:
                    tool_content = _dispatch_tool(name, args, bridge, log=log)
                except (ConnectionError, OSError) as exc:
                    raise RuntimeError(
                        "Lost connection to Blender: %s\nMake sure the server "
                        "is running in Blender (AI Agent tab > Start)." % exc)
            messages.append({
                "role": "tool",
                "tool_call_id": call.get("id", "0"),
                "content": tool_content if tool_content is not None else "done",
            })

        if done_summary is not None:
            log("\n=== Done: %s ===" % done_summary)
            return done_summary

    log("\n[reached max iterations (%d); stopping]" % max_iters)
    return "Stopped after %d steps." % max_iters


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def _connect_with_help(host, port):
    try:
        bridge = BlenderBridge(host, port)
    except (ConnectionError, OSError) as exc:
        print("Could not connect to Blender at %s:%d (%s)." % (host, port, exc))
        print("Open Blender -> 3D Viewport -> press N -> 'AI Agent' tab -> "
              "'Start AI Agent Server', then retry.")
        sys.exit(1)
    reply = bridge.call("ping")
    if reply.get("ok"):
        info = reply["result"]
        print("Connected to Blender %s (scene: %s)."
              % (info.get("blender"), info.get("scene")))
    return bridge


def _run_exec_file(path, bridge):
    with open(path, "r", encoding="utf-8") as fh:
        code = fh.read()
    reply = bridge.call("exec", code=code)
    result = reply.get("result") or {}
    if result.get("stdout"):
        print(result["stdout"], end="")
    if result.get("error"):
        print(result["error"], file=sys.stderr)
        sys.exit(1)


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Free AI agent that builds things in Blender.")
    parser.add_argument("task", nargs="?",
                        help="What you want built, e.g. \"a small windmill\". "
                             "If omitted, starts interactive chat mode.")
    parser.add_argument("--provider", default=os.environ.get("LLM_PROVIDER", "ollama"),
                        choices=sorted(PROVIDERS.keys()),
                        help="LLM provider (default: ollama - free, local).")
    parser.add_argument("--model", default=os.environ.get("LLM_MODEL"),
                        help="Override the model name.")
    parser.add_argument("--base-url", default=os.environ.get("LLM_BASE_URL"),
                        help="Override the API base URL (any OpenAI-compatible server).")
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--max-iters", type=int, default=30)
    parser.add_argument("--exec", metavar="FILE",
                        help="Skip the LLM: just run a .py file inside Blender.")
    args = parser.parse_args(argv)

    bridge = _connect_with_help(args.host, args.port)

    if args.exec:
        _run_exec_file(args.exec, bridge)
        return

    llm = LLMClient(provider=args.provider, model=args.model,
                    base_url=args.base_url)
    print("Using LLM: %s via %s (free: %s)"
          % (llm.model, llm.provider,
             "yes" if args.provider in ("ollama", "groq", "gemini") else "no"))

    try:
        if args.task:
            run_task(args.task, bridge, llm, max_iters=args.max_iters)
        else:
            print("\nInteractive mode. Describe what you want built. "
                  "Commands: /scene - show scene info, /undo - undo last step, "
                  "/quit - exit.\n")
            while True:
                try:
                    task = input("you > ").strip()
                except (EOFError, KeyboardInterrupt):
                    print()
                    break
                if not task:
                    continue
                if task in ("/quit", "/exit"):
                    break
                if task == "/scene":
                    reply = bridge.call("scene_info")
                    print(json.dumps(reply.get("result", reply), indent=2))
                    continue
                if task == "/undo":
                    print(bridge.call("undo"))
                    continue
                try:
                    run_task(task, bridge, llm, max_iters=args.max_iters)
                except RuntimeError as exc:
                    print("\n[agent error] %s" % exc)
    except RuntimeError as exc:
        print("\n[agent error] %s" % exc)
        if "ollama" in str(exc).lower() or "11434" in str(exc):
            print("\nOllama quick start:")
            print("  1. Download Ollama: https://ollama.com")
            print("  2. ollama pull qwen2.5-coder:7b")
            print("  3. Make sure Ollama is running, then try again.")
        sys.exit(1)
    finally:
        bridge.close()


if __name__ == "__main__":
    main()
