# /modules/self_improve.py
"""Self-extension and self-modification.

This is the module that lets JARVIS grow:

* **Search GitHub** for repositories that do something he cannot yet do
  (the public search API needs no key — a ``GITHUB_TOKEN`` only raises the
  rate limit).
* **Integrate a repository** by cloning it into ``data/repos`` and having the
  local LLM write a JARVIS *adapter* — a real ``BaseModule`` with ``@tool``
  methods — into ``plugins/``. The adapter is compiled, imported, instantiated
  and registered live, so the new skill is usable in the same conversation and
  again after a restart.
* **Rewrite his own source code**: read a file, describe the change, get a
  unified diff, and apply it behind a safety net — backup, syntax check, test
  suite, hot reload, git commit, and automatic rollback if anything fails.

Safety is deliberately conservative: code edits and plugin installs are
``dangerous`` tools (so they route through :class:`utils.security.SecurityGuard`
confirmation), ``self_improve.protected`` files can never be rewritten, pip
installs are off until you enable them, and every accepted change is recorded
in SQLite with a restorable backup.
"""

from __future__ import annotations

import ast
import difflib
import importlib
import importlib.util
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from modules.base import BaseModule, ModuleResult, strip_command_prefix, tool
from utils.helpers import (
    ensure_dir,
    extract_code_blocks,
    human_bytes,
    run_blocking,
    slugify,
    ssl_verify,
    truncate,
)

GITHUB_API = "https://api.github.com"

#: Files JARVIS may never rewrite, on top of whatever config adds.
ALWAYS_PROTECTED = {"utils/security.py", "modules/self_improve.py"}

#: Directories that are part of "himself" for the purposes of self-editing.
SOURCE_DIRS = ("core", "interfaces", "modules", "utils", "plugins", "tests")

ADAPTER_TEMPLATE = '''# /plugins/{slug}.py
"""JARVIS skill adapter for {repo}.

Generated by the self_improve module on {stamp}.
Upstream: {url}
Clone: {clone}
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from modules.base import BaseModule, ModuleResult, tool


class {classname}(BaseModule):
    """Wraps {repo} as a JARVIS skill."""

    name = "{slug}"
    description = {description!r}
    intent_examples = {examples!r}

    @tool(
        description="Show what this skill is and how to use it.",
        params={{}},
        keywords={keywords!r},
    )
    async def about(self) -> ModuleResult:
        """Describe the integrated repository."""
        return ModuleResult.ok(
            "{repo} is integrated but has no generated tools yet. "
            "Its source is in {clone}. Ask me to write a wrapper for a "
            "specific function and I'll extend this file."
        )
'''


class SelfImprove(BaseModule):
    """Give JARVIS the ability to extend and rewrite himself."""

    name = "self_improve"
    description = (
        "Self-extension and self-modification: search GitHub for projects, integrate a "
        "repository as a new skill, inspect and rewrite JARVIS's own source code, run his "
        "test suite, hot-reload modules, and roll changes back."
    )
    intent_examples = [
        "search github for a python music player library",
        "integrate that repository into yourself",
        "add a new skill for controlling spotify",
        "improve your own weather tool",
        "show me your own source code",
        "run your tests",
        "undo your last change",
    ]

    def __init__(self, config: Any, llm: Any = None, security: Any = None) -> None:
        """Read the ``self_improve`` configuration and prepare bookkeeping."""
        super().__init__(config, llm=llm, security=security)
        section = config.section("self_improve")
        self.enabled: bool = bool(section.get("enabled", True))
        self.allow_code_edit: bool = bool(section.get("allow_code_edit", True))
        self.allow_plugin_install: bool = bool(section.get("allow_plugin_install", True))
        self.allow_pip_install: bool = bool(section.get("allow_pip_install", False))
        self.run_tests: bool = bool(section.get("run_tests_after_edit", True))
        self.test_command: str = str(section.get("test_command", "tests/test_smoke.py"))
        self.test_timeout: float = float(section.get("test_timeout", 900))
        self.git_commit_enabled: bool = bool(section.get("git_commit", True))
        self.auto_reload: bool = bool(section.get("auto_reload", True))
        self.max_file_bytes: int = int(section.get("max_file_bytes", 400_000))
        self.max_results: int = int(section.get("max_search_results", 8))
        self.token_env: str = str(section.get("github_token_env", "GITHUB_TOKEN"))
        self.keep_backups: int = int(section.get("keep_backups", 40))

        self.root: Path = Path(getattr(config, "root", Path.cwd()))
        self.plugins_dir: Path = config.resolve(section.get("plugins_dir", "plugins"))
        self.repos_dir: Path = config.resolve(section.get("repos_dir", "data/repos"))
        self.backup_dir: Path = config.resolve(section.get("backup_dir", "data/backups"))
        self.protected: List[str] = list(
            dict.fromkeys(
                [str(item) for item in (section.get("protected") or [])]
                + sorted(ALWAYS_PROTECTED)
            )
        )
        self.db_path: Path = config.resolve(config.get("database.path", "data/jarvis.db"))

        #: Set by :class:`core.brain.Brain` so new skills can be registered live.
        self.brain: Optional[Any] = None
        self._init_db()

    # ------------------------------------------------------------------ infra
    async def setup(self) -> None:
        """Make sure the plugin, repo and backup directories exist."""
        for directory in (self.plugins_dir, self.repos_dir, self.backup_dir):
            try:
                ensure_dir(directory)
            except Exception as exc:
                self.log.debug("Could not create %s: %s", directory, exc)
        readme = self.plugins_dir / "README.md"
        if not readme.exists():
            try:
                readme.write_text(
                    "# Plugins\n\nEvery `.py` file here that defines a `BaseModule` "
                    "subclass is loaded as a JARVIS skill at start-up.\n"
                    "Files in this folder are generated by the `self_improve` module — "
                    "read them before trusting them.\n",
                    encoding="utf-8",
                )
            except Exception:
                pass

    def _connect(self) -> sqlite3.Connection:
        """Open the shared SQLite database."""
        ensure_dir(self.db_path.parent)
        connection = sqlite3.connect(str(self.db_path), timeout=30)
        connection.row_factory = sqlite3.Row
        return connection

    def _init_db(self) -> None:
        """Create the change-log table."""
        try:
            with self._connect() as connection:
                connection.executescript(
                    """
                    CREATE TABLE IF NOT EXISTS self_changes (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        created_at TEXT NOT NULL,
                        kind TEXT NOT NULL,
                        target TEXT NOT NULL,
                        description TEXT,
                        backup TEXT,
                        tests TEXT,
                        committed TEXT,
                        reverted INTEGER DEFAULT 0
                    );
                    CREATE INDEX IF NOT EXISTS idx_changes_target ON self_changes(target);
                    """
                )
        except Exception as exc:
            self.log.debug("Change log init failed: %s", exc)

    def _record(
        self,
        kind: str,
        target: str,
        description: str,
        backup: str = "",
        tests: str = "",
        committed: str = "",
    ) -> int:
        """Write a row into the change log and return its id."""
        try:
            with self._connect() as connection:
                cursor = connection.execute(
                    "INSERT INTO self_changes"
                    " (created_at, kind, target, description, backup, tests, committed)"
                    " VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        datetime.now().isoformat(timespec="seconds"),
                        kind,
                        target,
                        truncate(description, 500),
                        backup,
                        tests,
                        committed,
                    ),
                )
                return int(cursor.lastrowid or 0)
        except Exception as exc:
            self.log.debug("Could not record change: %s", exc)
            return 0

    # ---------------------------------------------------------- offline route
    def offline_router(self, command: str) -> Optional[tuple[str, Dict[str, Any]]]:
        """Rule-based routing used when no LLM is available."""
        text = strip_command_prefix(command)
        lowered = text.lower()

        if "github" in lowered and any(
            word in lowered for word in ("search", "find", "look for", "look up")
        ):
            query = re.sub(
                r".*?(?:search|find|look for|look up)\s+(?:github\s+)?(?:for\s+)?", "", lowered
            ).replace("on github", "").strip()
            return "search_github", {"query": query or text}
        if "integrate" in lowered or "install the repo" in lowered or "add the repo" in lowered:
            match = re.search(r"[\w.-]+/[\w.-]+", text)
            return "integrate_repo", {"repo": match.group(0) if match else text}
        if "plugin" in lowered and any(w in lowered for w in ("list", "what", "show")):
            return "list_plugins", {}
        if "plugin" in lowered and any(w in lowered for w in ("remove", "delete", "uninstall")):
            match = re.search(r"(?:remove|delete|uninstall)\s+(?:the\s+)?(\w+)", lowered)
            return "remove_plugin", {"name": match.group(1) if match else text}
        if any(word in lowered for word in ("run your test", "self test", "test yourself",
                                            "run the tests")):
            return "run_self_tests", {}
        if any(word in lowered for word in ("undo", "roll back", "rollback", "revert")):
            return "rollback", {}
        if ("history" in lowered and ("change" in lowered or "edit" in lowered)) or any(
            phrase in lowered
            for phrase in ("what have you changed", "what did you change",
                           "changed about yourself", "your changes", "change log",
                           "changelog")
        ):
            return "change_history", {}
        if any(phrase in lowered for phrase in ("what can you do to yourself",
                                                "self improvement status",
                                                "self-improvement status")):
            return "self_status", {}
        if "suggest" in lowered or "what would you improve" in lowered:
            return "suggest_improvements", {"focus": text}
        if any(word in lowered for word in ("your code", "your source", "own code",
                                            "source code")):
            match = re.search(r"[\w/]+\.py", text)
            if match:
                return "read_own_code", {"path": match.group(0)}
            return "code_map", {}
        if "reload" in lowered:
            match = re.search(r"reload\s+(?:the\s+)?(\w+)", lowered)
            return "reload_module", {"name": match.group(1) if match else ""}
        if any(word in lowered for word in ("improve", "modify", "rewrite", "fix your",
                                            "change your", "edit your", "upgrade your")):
            match = re.search(r"[\w/]+\.py", text)
            return "edit_own_code", {"path": match.group(0) if match else "",
                                     "instruction": text}
        return "code_map", {}

    # ---------------------------------------------------------------- GitHub
    async def _github(self, path: str, params: Optional[Dict[str, Any]] = None,
                      raw: bool = False) -> Optional[Any]:
        """Call the public GitHub API. Returns parsed JSON, text, or ``None``."""
        try:
            import httpx
        except Exception:
            return None

        headers = {
            "Accept": "application/vnd.github.raw" if raw else "application/vnd.github+json",
            "User-Agent": "JARVIS-local-assistant",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        token = os.environ.get(self.token_env, "").strip()
        if token:
            headers["Authorization"] = f"Bearer {token}"
        try:
            async with httpx.AsyncClient(
                timeout=25, follow_redirects=True, verify=ssl_verify()
            ) as client:
                response = await client.get(
                    f"{GITHUB_API}{path}", params=params or {}, headers=headers
                )
                if response.status_code == 403 and "rate limit" in response.text.lower():
                    self.log.warning("GitHub rate limit reached.")
                    return {"__error__": "rate_limit"}
                response.raise_for_status()
                return response.text if raw else response.json()
        except Exception as exc:
            self.log.debug("GitHub request failed: %s", truncate(str(exc), 160))
            return None

    @tool(
        description="Search GitHub for repositories (no API key needed).",
        params={
            "query": {"type": "string", "description": "What to look for", "required": True},
            "language": {"type": "string", "description": "Filter by language",
                         "default": "python"},
            "min_stars": {"type": "integer", "description": "Minimum stars", "default": 25},
            "limit": {"type": "integer", "description": "How many results", "default": 8},
        },
        keywords=["search github", "find a repo", "github for", "is there a library",
                  "open source project for", "find a package"],
        examples=['search_github(query="home assistant control", min_stars=100)'],
    )
    async def search_github(
        self, query: str, language: str = "python", min_stars: int = 25, limit: int = 8
    ) -> ModuleResult:
        """Search public repositories, sorted by stars."""
        query = (query or "").strip()
        if not query:
            return ModuleResult.fail("What should I look for on GitHub, sir?")

        terms = [query]
        if language:
            terms.append(f"language:{language}")
        if min_stars:
            terms.append(f"stars:>={int(min_stars)}")
        payload = await self._github(
            "/search/repositories",
            {
                "q": " ".join(terms),
                "sort": "stars",
                "order": "desc",
                "per_page": max(1, min(int(limit or self.max_results), 20)),
            },
        )
        if payload is None:
            return ModuleResult.fail(
                "GitHub is unreachable — check the network. (No key is needed for search; "
                f"set ${self.token_env} only if you hit the rate limit.)"
            )
        if isinstance(payload, dict) and payload.get("__error__") == "rate_limit":
            return ModuleResult.fail(
                f"GitHub's anonymous rate limit is exhausted. Export a free personal token "
                f"as ${self.token_env} and I'll get 30 searches a minute instead of 10."
            )

        items = (payload or {}).get("items", []) if isinstance(payload, dict) else []
        if not items:
            return ModuleResult.ok(f"Nothing on GitHub matches '{query}'.", results=[])

        results: List[Dict[str, Any]] = []
        lines: List[str] = []
        for index, item in enumerate(items, 1):
            licence = ((item.get("license") or {}).get("spdx_id") or "no licence")
            entry = {
                "repo": item.get("full_name", ""),
                "description": truncate(item.get("description") or "", 180),
                "stars": int(item.get("stargazers_count", 0)),
                "language": item.get("language") or "",
                "license": licence,
                "url": item.get("html_url", ""),
                "clone_url": item.get("clone_url", ""),
                "updated": (item.get("pushed_at") or "")[:10],
                "topics": item.get("topics", [])[:5],
            }
            results.append(entry)
            lines.append(
                f"{index}. {entry['repo']} ★{entry['stars']:,} · {entry['language']} · "
                f"{entry['license']} · updated {entry['updated']}\n"
                f"   {entry['description']}\n   {entry['url']}"
            )

        top = results[0]
        return ModuleResult(
            success=True,
            output=f"GitHub results for '{query}':\n" + "\n".join(lines),
            speak=f"The strongest candidate is {top['repo']} with "
                  f"{top['stars']:,} stars. {top['description']}",
            data={"results": results, "query": query},
        ).offering(
            "self_improve.integrate_repo",
            {"repo": top["repo"]},
            f"Shall I integrate {top['repo']} into myself?",
        )

    @tool(
        description="Show details and the README of a GitHub repository.",
        params={
            "repo": {"type": "string", "description": "owner/name", "required": True},
        },
        keywords=["tell me about the repo", "repo details", "what does that project do",
                  "show me the readme"],
    )
    async def repo_details(self, repo: str) -> ModuleResult:
        """Fetch metadata plus a trimmed README for a repository."""
        slug = self._normalise_repo(repo)
        if not slug:
            return ModuleResult.fail("Give me the repository as 'owner/name', sir.")
        meta = await self._github(f"/repos/{slug}")
        if not isinstance(meta, dict) or meta.get("__error__"):
            return ModuleResult.fail(f"Could not read {slug} from GitHub.")
        readme = await self._github(f"/repos/{slug}/readme", raw=True)
        summary = (
            f"{meta.get('full_name')} — {meta.get('description') or 'no description'}\n"
            f"★ {meta.get('stargazers_count', 0):,} · forks {meta.get('forks_count', 0):,} · "
            f"{meta.get('language') or 'mixed'} · "
            f"{((meta.get('license') or {}).get('spdx_id') or 'no licence')} · "
            f"updated {(meta.get('pushed_at') or '')[:10]}\n{meta.get('html_url')}"
        )
        if isinstance(readme, str) and readme.strip():
            summary += "\n\nREADME (trimmed):\n" + truncate(readme.strip(), 2000)
        return ModuleResult(
            success=True,
            output=summary,
            speak=f"{slug}: {truncate(meta.get('description') or '', 200)}",
            data={"repo": slug, "meta": {
                "stars": meta.get("stargazers_count", 0),
                "license": (meta.get("license") or {}).get("spdx_id", ""),
                "clone_url": meta.get("clone_url", ""),
                "default_branch": meta.get("default_branch", "main"),
            }},
        ).offering(
            "self_improve.integrate_repo", {"repo": slug},
            f"Shall I integrate {slug}?",
        )

    @staticmethod
    def _normalise_repo(repo: str) -> str:
        """Turn a URL or free text into ``owner/name``."""
        text = (repo or "").strip().rstrip("/")
        match = re.search(r"github\.com[:/]+([\w.-]+/[\w.-]+?)(?:\.git)?$", text)
        if match:
            return match.group(1)
        match = re.search(r"^([\w.-]+/[\w.-]+?)(?:\.git)?$", text)
        if match:
            return match.group(1)
        match = re.search(r"([\w.-]+/[\w.-]+)", text)
        return match.group(1) if match else ""

    # ------------------------------------------------------------ integration
    @tool(
        description=(
            "Clone a GitHub repository and write a JARVIS skill adapter for it, making its "
            "functionality available as new tools."
        ),
        params={
            "repo": {"type": "string", "description": "owner/name, URL or local path",
                     "required": True},
            "name": {"type": "string", "description": "Skill name (default: repo name)",
                     "default": ""},
            "goal": {"type": "string",
                     "description": "What the new skill should let JARVIS do", "default": ""},
            "pip_install": {"type": "boolean",
                            "description": "Also pip install the repo's requirements",
                            "default": False},
        },
        dangerous=True,
        keywords=["integrate that repo", "add that project", "install that plugin",
                  "make that a skill", "absorb that repository", "learn that library"],
        examples=['integrate_repo(repo="psf/requests-html", goal="scrape javascript pages")'],
    )
    async def integrate_repo(
        self, repo: str, name: str = "", goal: str = "", pip_install: bool = False
    ) -> ModuleResult:
        """Clone a repository and generate, validate and register a skill adapter."""
        if not self.allow_plugin_install:
            return ModuleResult.fail(
                "Plugin installation is disabled — set self_improve.allow_plugin_install: "
                "true in config.yaml if you trust me with it."
            )

        source = (repo or "").strip()
        local_source = Path(source).expanduser()
        is_local = local_source.exists()
        slug_source = local_source.name if is_local else self._normalise_repo(source)
        if not slug_source:
            return ModuleResult.fail("I need a repository as 'owner/name' or a URL, sir.")

        skill = slugify(name or slug_source.split("/")[-1], 40).replace("-", "_").strip("_")
        skill = re.sub(r"[^a-z0-9_]", "", skill.lower()) or "skill"
        if skill in {"base", "self_improve"} or (self.brain and skill in
                                                 getattr(self.brain, "modules", {})):
            skill = f"{skill}_skill"

        clone_url = str(local_source) if is_local else f"https://github.com/{slug_source}.git"
        destination = self.repos_dir / skill

        def _clone() -> Tuple[bool, str]:
            """Shallow-clone the repository, refreshing an existing copy."""
            try:
                ensure_dir(self.repos_dir)
                if destination.exists():
                    shutil.rmtree(destination, ignore_errors=True)
                completed = subprocess.run(
                    ["git", "clone", "--depth", "1", clone_url, str(destination)],
                    capture_output=True, text=True, timeout=300,
                )
                if completed.returncode != 0:
                    return False, (completed.stderr or completed.stdout)[-400:]
                return True, ""
            except FileNotFoundError:
                return False, "git is not installed — install it and try again."
            except Exception as exc:
                return False, str(exc)

        cloned, error = await run_blocking(_clone)
        if not cloned:
            return ModuleResult.fail(f"Clone failed: {truncate(error, 300)}")

        survey = await run_blocking(self._survey_repo, destination)
        installed = ""
        if pip_install:
            result = await self.install_package(
                package=str(destination), from_path=True
            )
            installed = result.output

        adapter = await self._write_adapter(skill, slug_source, destination, survey, goal)
        if not adapter.success:
            return adapter

        registered = await self._register_plugin(skill, adapter.data.get("path", ""))
        self._record(
            "plugin",
            skill,
            f"Integrated {slug_source} ({survey['files']} files)",
            backup="",
            tests="",
            committed=await self._git_commit(
                [adapter.data.get("path", "")], f"self: integrate {slug_source} as {skill}"
            ),
        )
        tools = ", ".join(registered.get("tools", [])) or "about"
        note = f"\n{installed}" if installed else ""
        return ModuleResult(
            success=True,
            output=(
                f"Integrated {slug_source} as the '{skill}' skill.\n"
                f"  source : {destination}\n"
                f"  adapter: {adapter.data.get('path')}\n"
                f"  tools  : {tools}\n"
                f"  status : {registered.get('status')}"
                f"{note}"
            ),
            speak=f"{slug_source} is now part of me, sir. New skill '{skill}' with "
                  f"{len(registered.get('tools', []))} tools.",
            data={"skill": skill, "repo": slug_source, "tools": registered.get("tools", []),
                  "adapter": adapter.data.get("path", "")},
        )

    def _survey_repo(self, path: Path) -> Dict[str, Any]:
        """Collect the facts the LLM needs to write an adapter."""
        info: Dict[str, Any] = {
            "readme": "", "files": 0, "python_files": [], "package": "",
            "entry_points": [], "requirements": [], "size": 0,
        }
        try:
            for candidate in ("README.md", "README.rst", "README.txt", "readme.md"):
                readme = path / candidate
                if readme.exists():
                    info["readme"] = truncate(
                        readme.read_text(encoding="utf-8", errors="replace"), 4000
                    )
                    break

            python_files: List[Tuple[int, Path]] = []
            for file in path.rglob("*.py"):
                if any(part in {".git", "test", "tests", "docs", "examples", "build"}
                       for part in file.parts):
                    continue
                try:
                    size = file.stat().st_size
                except Exception:
                    continue
                info["files"] += 1
                info["size"] += size
                python_files.append((size, file))
            python_files.sort(reverse=True)
            info["python_files"] = [
                str(file.relative_to(path)) for _, file in python_files[:20]
            ]

            for meta_name in ("pyproject.toml", "setup.py", "setup.cfg"):
                meta = path / meta_name
                if not meta.exists():
                    continue
                text = meta.read_text(encoding="utf-8", errors="replace")
                match = re.search(r'name\s*=\s*["\']([\w.-]+)["\']', text)
                if match:
                    info["package"] = match.group(1)
                    break
            if not info["package"]:
                for child in path.iterdir():
                    if child.is_dir() and (child / "__init__.py").exists():
                        info["package"] = child.name
                        break

            requirements = path / "requirements.txt"
            if requirements.exists():
                info["requirements"] = [
                    line.strip()
                    for line in requirements.read_text(
                        encoding="utf-8", errors="replace"
                    ).splitlines()[:25]
                    if line.strip() and not line.startswith("#")
                ]

            # Public functions of the package's __init__ or the biggest module.
            probe = None
            if info["package"]:
                candidate = path / info["package"] / "__init__.py"
                probe = candidate if candidate.exists() else None
            if probe is None and python_files:
                probe = python_files[0][1]
            if probe is not None:
                try:
                    tree = ast.parse(probe.read_text(encoding="utf-8", errors="replace"))
                    for node in tree.body:
                        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef,
                                             ast.ClassDef)) and not node.name.startswith("_"):
                            signature = node.name
                            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                                args = [a.arg for a in node.args.args if a.arg != "self"]
                                signature = f"{node.name}({', '.join(args)})"
                            doc = (ast.get_docstring(node) or "").split("\n")[0]
                            info["entry_points"].append(
                                f"{signature} — {truncate(doc, 100)}" if doc else signature
                            )
                except Exception:
                    pass
                info["entry_points"] = info["entry_points"][:20]
        except Exception as exc:
            self.log.debug("Repo survey failed: %s", exc)
        return info

    async def _write_adapter(
        self, skill: str, repo: str, clone: Path, survey: Dict[str, Any], goal: str
    ) -> ModuleResult:
        """Ask the LLM for an adapter module, validate it, and write it to disk."""
        classname = "".join(part.title() for part in skill.split("_")) or "Skill"
        target = self.plugins_dir / f"{skill}.py"
        ensure_dir(self.plugins_dir)

        fallback = ADAPTER_TEMPLATE.format(
            slug=skill,
            classname=classname,
            repo=repo,
            url=f"https://github.com/{repo}",
            clone=clone,
            stamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            description=f"Skill generated from the {repo} repository.",
            examples=[f"use {skill}"],
            keywords=[skill, repo.split("/")[-1].lower()],
        )

        if self.llm is None or not getattr(self.llm, "available", False):
            await run_blocking(target.write_text, fallback, "utf-8")
            return ModuleResult(
                success=True,
                output=f"Wrote a stub adapter (no LLM available) to {target}.",
                data={"path": str(target), "generated": False},
            )

        prompt = self._adapter_prompt(skill, classname, repo, clone, survey, goal)
        code = ""
        error = ""
        for attempt in range(1, 3):
            raw = await self.llm.complete(
                prompt if attempt == 1 else
                f"{prompt}\n\nYour previous attempt failed with:\n{error}\n"
                "Return the corrected COMPLETE file.",
                temperature=0.2,
                max_tokens=2200,
            )
            candidate = self._extract_python(raw)
            if not candidate:
                error = "no python code block found in the response"
                continue
            ok, error = self._validate_adapter(candidate, skill)
            if ok:
                code = candidate
                break
            self.log.debug("Adapter attempt %d rejected: %s", attempt, error)

        if not code:
            await run_blocking(target.write_text, fallback, "utf-8")
            return ModuleResult(
                success=True,
                output=(
                    f"The generated adapter didn't pass validation ({truncate(error, 160)}), "
                    f"so I wrote a safe stub to {target} instead. The cloned source is at "
                    f"{clone} — ask me to write a wrapper for a specific function."
                ),
                data={"path": str(target), "generated": False, "error": error},
            )

        header = (
            f"# /plugins/{skill}.py\n"
            f"# Generated by JARVIS self_improve on "
            f"{datetime.now():%Y-%m-%d %H:%M} from {repo}\n"
            f"# Upstream: https://github.com/{repo}\n"
            f"# Local clone: {clone}\n"
        )
        if not code.startswith("#"):
            code = header + code
        await run_blocking(target.write_text, code, "utf-8")
        return ModuleResult(
            success=True,
            output=f"Adapter written to {target}.",
            data={"path": str(target), "generated": True},
        )

    def _adapter_prompt(
        self, skill: str, classname: str, repo: str, clone: Path,
        survey: Dict[str, Any], goal: str
    ) -> str:
        """Build the prompt that asks the LLM for a plugin module."""
        return f"""You are extending JARVIS, a local Python assistant, with a new skill that
wraps the repository {repo}.

REPOSITORY FACTS
  local clone : {clone}
  package     : {survey.get('package') or 'unknown'}
  python files: {', '.join(survey.get('python_files', [])[:10]) or 'none found'}
  public API  : {'; '.join(survey.get('entry_points', [])[:12]) or 'unknown'}
  requirements: {', '.join(survey.get('requirements', [])[:10]) or 'none listed'}
  goal        : {goal or 'expose the most useful functionality as JARVIS tools'}

README (trimmed)
{truncate(survey.get('readme', ''), 2500)}

Write ONE complete Python module. Hard requirements:
1. Start with the comment line: # /plugins/{skill}.py
2. `from modules.base import BaseModule, ModuleResult, tool`
3. Define `class {classname}(BaseModule)` with:
     name = "{skill}"
     description = "<one sentence>"
     intent_examples = [<3 example user phrases>]
4. Between two and five `@tool(...)`-decorated `async def` methods. Each takes
   simple parameters (str/int/bool) and returns `ModuleResult`. Give every tool
   a `description`, a `params` dict and `keywords`.
5. Import the third-party library LAZILY inside the methods, wrapped in
   try/except, and return `ModuleResult.fail("... pip install X ...")` when the
   import fails. Never let an exception escape.
6. If the library needs a paid API key, do not use it — expose only free
   functionality and say so in the failure message.
7. Add `sys.path` handling if the code must be imported from the clone:
   `sys.path.insert(0, r"{clone}")` inside the method before importing.
8. Type hints and docstrings on every method. No TODOs. No placeholders.
9. Never run shell commands, never delete files, never read secrets.

Return ONLY the code in a single ```python block."""

    @staticmethod
    def _extract_python(text: str, require_class: bool = True) -> str:
        """Pull Python source out of an LLM response.

        Handles the awkward case where the file being rewritten itself contains
        triple backticks, which breaks naive fence matching.

        Args:
            text: The raw model response.
            require_class: Only accept blocks that define a class.

        Returns:
            The extracted source, or ``""`` when nothing usable was found.
        """
        raw = text or ""
        blocks = extract_code_blocks(raw)
        for language, code in blocks:
            if language in ("", "python", "py") and (not require_class or "class" in code):
                return code.strip()

        # Unbalanced or nested fences: take everything after the first opening
        # fence and drop a trailing one.
        match = re.search(r"```(?:python|py)?[ \t]*\n", raw)
        if match:
            body = raw[match.end():]
            body = re.sub(r"\n```[\s\S]*$", "\n", body)
            if "def " in body or "class " in body:
                return body.strip()

        stripped = raw.strip()
        if stripped.startswith(("#", "from ", "import ", '"""')) and "def " in stripped:
            return stripped
        return ""

    def _validate_adapter(self, code: str, skill: str) -> Tuple[bool, str]:
        """Static safety and structure checks for generated plugin code."""
        if len(code) > self.max_file_bytes:
            return False, "generated file is implausibly large"
        try:
            tree = ast.parse(code)
        except SyntaxError as exc:
            return False, f"syntax error on line {exc.lineno}: {exc.msg}"

        banned = {
            "os.system", "subprocess.run", "subprocess.Popen", "subprocess.call",
            "shutil.rmtree", "eval", "exec", "compile", "__import__",
        }
        source = code.replace(" ", "")
        for pattern in banned:
            if pattern.replace(" ", "") + "(" in source:
                return False, f"generated code calls {pattern}, which I will not accept"

        has_class = any(
            isinstance(node, ast.ClassDef)
            and any(getattr(base, "id", getattr(base, "attr", "")) == "BaseModule"
                    for base in node.bases)
            for node in ast.walk(tree)
        )
        if not has_class:
            return False, "no BaseModule subclass found"
        if f'"{skill}"' not in code and f"'{skill}'" not in code:
            return False, f"the module does not set name = '{skill}'"
        if "@tool" not in code:
            return False, "no @tool methods were defined"
        return True, ""

    async def _register_plugin(self, skill: str, path: str) -> Dict[str, Any]:
        """Import a plugin file and register it with the running brain."""
        result: Dict[str, Any] = {"status": "written to disk", "tools": []}
        if not path:
            return result
        try:
            instance = await run_blocking(load_plugin, Path(path), self.config,
                                          self.llm, self.security)
            if instance is None:
                result["status"] = "written, but no BaseModule subclass could be imported"
                return result
            await instance.setup()
            result["tools"] = list(instance.tools)
            if self.brain is not None and hasattr(self.brain, "register_module"):
                self.brain.register_module(instance)
                result["status"] = "loaded and active right now"
            else:
                result["status"] = "loaded; active after restart"
        except Exception as exc:
            result["status"] = f"import failed ({truncate(str(exc), 160)}) — file kept for review"
        return result

    @tool(
        description="List the skills that have been added to JARVIS as plugins.",
        params={},
        keywords=["list plugins", "what skills do you have", "installed plugins",
                  "what have you learned"],
    )
    async def list_plugins(self) -> ModuleResult:
        """Show generated plugin adapters and their status."""
        files = sorted(
            file for file in self.plugins_dir.glob("*.py") if not file.name.startswith("_")
        ) if self.plugins_dir.exists() else []
        if not files:
            return ModuleResult.ok(
                "No plugins yet. Ask me to search GitHub for something and integrate it.",
                plugins=[],
            )
        active = getattr(self.brain, "modules", {}) if self.brain else {}
        rows = []
        listing = []
        for file in files:
            skill = file.stem
            loaded = skill in active
            tools = len(active[skill].tools) if loaded else 0
            clone = self.repos_dir / skill
            rows.append({"name": skill, "path": str(file), "loaded": loaded, "tools": tools})
            listing.append(
                f"  {skill:<20} {'active' if loaded else 'inactive'} · "
                f"{tools} tools · {human_bytes(file.stat().st_size)}"
                + (f" · source {clone}" if clone.exists() else "")
            )
        return ModuleResult(
            success=True,
            output=f"{len(files)} plugin(s):\n" + "\n".join(listing),
            data={"plugins": rows},
        )

    @tool(
        description="Remove an installed plugin skill and its cloned source.",
        params={
            "name": {"type": "string", "description": "Plugin name", "required": True},
            "keep_source": {"type": "boolean", "description": "Keep the cloned repository",
                            "default": False},
        },
        dangerous=True,
        keywords=["remove plugin", "uninstall skill", "delete that plugin", "forget that skill"],
    )
    async def remove_plugin(self, name: str, keep_source: bool = False) -> ModuleResult:
        """Delete a plugin adapter (and optionally its clone) and unregister it."""
        skill = re.sub(r"[^a-z0-9_]", "", (name or "").lower().replace("-", "_"))
        target = self.plugins_dir / f"{skill}.py"
        if not skill or not target.exists():
            return ModuleResult.fail(f"No plugin called '{name}'.")

        backup = await run_blocking(self._backup_file, target)
        try:
            target.unlink()
        except Exception as exc:
            return ModuleResult.fail(f"Could not delete {target}: {exc}")
        removed_source = ""
        clone = self.repos_dir / skill
        if not keep_source and clone.exists():
            await run_blocking(shutil.rmtree, clone, True)
            removed_source = f" and its source at {clone}"
        if self.brain is not None and hasattr(self.brain, "unregister_module"):
            self.brain.unregister_module(skill)
        self._record("plugin_removed", skill, f"Removed plugin {skill}", backup=backup)
        return ModuleResult.ok(
            f"Removed the '{skill}' skill{removed_source}. A backup of the adapter is at "
            f"{backup}."
        )

    @tool(
        description="Install a Python package into JARVIS's own virtual environment.",
        params={
            "package": {"type": "string", "description": "Package name or local path",
                        "required": True},
            "from_path": {"type": "boolean", "description": "Treat 'package' as a local path",
                          "default": False},
        },
        dangerous=True,
        keywords=["pip install", "install the package", "add the dependency"],
    )
    async def install_package(self, package: str, from_path: bool = False) -> ModuleResult:
        """pip-install a dependency, if allowed by config."""
        if not self.allow_pip_install:
            return ModuleResult.fail(
                "Installing packages is disabled. Set self_improve.allow_pip_install: true "
                "in config.yaml if you want me to manage my own dependencies."
            )
        spec = (package or "").strip()
        if not spec or re.search(r"[;&|`$><]", spec):
            return ModuleResult.fail("That doesn't look like a safe package specification.")

        def _install() -> Tuple[int, str]:
            command = [sys.executable, "-m", "pip", "install", "--disable-pip-version-check"]
            if from_path:
                requirements = Path(spec) / "requirements.txt"
                if requirements.exists():
                    command += ["-r", str(requirements)]
                else:
                    command += [spec]
            else:
                command += [spec]
            completed = subprocess.run(command, capture_output=True, text=True, timeout=900)
            return completed.returncode, (completed.stdout + completed.stderr)[-1500:]

        code, output = await run_blocking(_install)
        if code != 0:
            return ModuleResult.fail(f"pip failed:\n{truncate(output, 600)}")
        self._record("pip", spec, f"Installed {spec}")
        return ModuleResult.ok(f"Installed {spec}.\n{truncate(output, 400)}")

    # ------------------------------------------------------------ self-coding
    def _resolve_source(self, path: str) -> Optional[Path]:
        """Resolve a project-relative source path, refusing anything outside."""
        candidate = (self.root / path).resolve() if not Path(path).is_absolute() \
            else Path(path).resolve()
        try:
            candidate.relative_to(self.root.resolve())
        except Exception:
            return None
        return candidate

    def _is_protected(self, path: Path) -> bool:
        """True when a file must never be rewritten."""
        try:
            relative = path.resolve().relative_to(self.root.resolve()).as_posix()
        except Exception:
            return True
        return any(relative == item or relative.startswith(item.rstrip("/") + "/")
                   for item in self.protected)

    @tool(
        description="List JARVIS's own source files so a change can be targeted.",
        params={"pattern": {"type": "string", "description": "Optional filter", "default": ""}},
        keywords=["your code", "your source files", "code map", "what files do you have",
                  "show your architecture"],
    )
    async def code_map(self, pattern: str = "") -> ModuleResult:
        """Summarise the project's own files with sizes and tool counts."""
        rows: List[Dict[str, Any]] = []

        def _scan() -> None:
            """Walk the source directories (blocking)."""
            for entry in ["main.py", "config.yaml"] + [
                str(file.relative_to(self.root))
                for directory in SOURCE_DIRS
                for file in sorted((self.root / directory).rglob("*.py"))
                if (self.root / directory).exists()
                and "__pycache__" not in file.parts
            ]:
                file = self.root / entry
                if not file.exists():
                    continue
                if pattern and pattern.lower() not in entry.lower():
                    continue
                try:
                    text = file.read_text(encoding="utf-8", errors="replace")
                except Exception:
                    continue
                rows.append(
                    {
                        "path": entry,
                        "lines": text.count("\n") + 1,
                        "bytes": len(text.encode("utf-8")),
                        "tools": text.count("@tool("),
                        "protected": self._is_protected(file),
                    }
                )

        await run_blocking(_scan)
        if not rows:
            return ModuleResult.fail("I can't find my own source — is the project moved?")
        total_lines = sum(row["lines"] for row in rows)
        total_tools = sum(row["tools"] for row in rows)
        listing = "\n".join(
            f"  {row['path']:<34} {row['lines']:>5} lines"
            + (f" · {row['tools']} tools" if row["tools"] else "")
            + ("  [protected]" if row["protected"] else "")
            for row in rows
        )
        return ModuleResult(
            success=True,
            output=(
                f"I am {len(rows)} files, {total_lines:,} lines, {total_tools} tools, "
                f"rooted at {self.root}:\n{listing}"
            ),
            speak=f"{len(rows)} source files, {total_lines:,} lines of me.",
            data={"files": rows, "root": str(self.root)},
        )

    @tool(
        description="Read one of JARVIS's own source files.",
        params={
            "path": {"type": "string", "description": "Project-relative path",
                     "required": True},
            "start": {"type": "integer", "description": "First line", "default": 1},
            "end": {"type": "integer", "description": "Last line (0 = end of file)",
                    "default": 0},
        },
        keywords=["show me your code", "read your own file", "print your source",
                  "what does your brain do"],
        examples=['read_own_code(path="modules/web_search.py", start=1, end=60)'],
    )
    async def read_own_code(self, path: str, start: int = 1, end: int = 0) -> ModuleResult:
        """Return a numbered slice of one of his own files."""
        target = self._resolve_source(path)
        if target is None or not target.exists() or not target.is_file():
            return ModuleResult.fail(f"I have no file at '{path}'. Try code_map first.")
        try:
            text = await run_blocking(target.read_text, "utf-8", "replace")
        except Exception as exc:
            return ModuleResult.fail(f"Could not read {path}: {exc}")

        lines = text.splitlines()
        first = max(1, int(start or 1))
        last = len(lines) if not end else min(len(lines), int(end))
        window = lines[first - 1: last]
        numbered = "\n".join(f"{first + index:>5} | {line}"
                             for index, line in enumerate(window))
        return ModuleResult(
            success=True,
            output=f"{path} (lines {first}-{last} of {len(lines)}):\n{truncate(numbered, 6000)}",
            speak=f"{path} is {len(lines)} lines long.",
            data={"path": path, "lines": len(lines), "protected": self._is_protected(target)},
        )

    def _backup_file(self, path: Path) -> str:
        """Copy a file into the backup directory; returns the backup path."""
        try:
            ensure_dir(self.backup_dir)
            stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            relative = path.resolve().relative_to(self.root.resolve()).as_posix()
            backup = self.backup_dir / f"{stamp}_{relative.replace('/', '_')}"
            shutil.copy2(path, backup)
            self._prune_backups()
            return str(backup)
        except Exception as exc:
            self.log.debug("Backup failed for %s: %s", path, exc)
            return ""

    def _prune_backups(self) -> None:
        """Keep only the newest ``keep_backups`` files."""
        try:
            backups = sorted(
                self.backup_dir.iterdir(), key=lambda item: item.stat().st_mtime, reverse=True
            )
            for stale in backups[self.keep_backups:]:
                stale.unlink(missing_ok=True)
        except Exception:
            pass

    async def _git_commit(self, paths: List[str], message: str) -> str:
        """Commit changed files to the local git repo. Returns a short status."""
        if not self.git_commit_enabled or not paths:
            return ""

        def _commit() -> str:
            try:
                if not (self.root / ".git").exists():
                    return ""
                add = subprocess.run(
                    ["git", "-C", str(self.root), "add"] + [p for p in paths if p],
                    capture_output=True, text=True, timeout=60,
                )
                if add.returncode != 0:
                    return ""
                commit = subprocess.run(
                    ["git", "-C", str(self.root),
                     "-c", "user.name=JARVIS", "-c", "user.email=jarvis@local",
                     "commit", "-m", message],
                    capture_output=True, text=True, timeout=60,
                )
                if commit.returncode != 0:
                    return ""
                head = subprocess.run(
                    ["git", "-C", str(self.root), "rev-parse", "--short", "HEAD"],
                    capture_output=True, text=True, timeout=30,
                )
                return head.stdout.strip()
            except Exception:
                return ""

        return await run_blocking(_commit)

    @tool(
        description=(
            "Modify JARVIS's own source code: describe the change and he rewrites the file, "
            "backs it up, checks the syntax, runs the tests and reloads himself."
        ),
        params={
            "path": {"type": "string", "description": "Project-relative file to change",
                     "required": True},
            "instruction": {"type": "string", "description": "What to change and why",
                            "required": True},
            "run_tests": {"type": "boolean",
                          "description": "Run the test suite before keeping the change",
                          "default": True},
        },
        dangerous=True,
        keywords=["change your own code", "modify yourself", "improve your", "rewrite your",
                  "fix your own", "add a tool to yourself", "upgrade yourself"],
        examples=['edit_own_code(path="modules/productivity.py", '
                  'instruction="add a tool that lists overdue todos")'],
    )
    async def edit_own_code(
        self, path: str, instruction: str, run_tests: bool = True
    ) -> ModuleResult:
        """Rewrite one of his own files under the LLM's direction, safely."""
        if not self.allow_code_edit:
            return ModuleResult.fail(
                "Self-editing is disabled — set self_improve.allow_code_edit: true if you "
                "want me rewriting myself, sir."
            )
        if self.llm is None or not getattr(self.llm, "available", False):
            return ModuleResult.fail(
                "I need the language model for that. Start Ollama and ask again."
            )

        target = self._resolve_source(path)
        if target is None or not target.exists():
            return ModuleResult.fail(f"I have no file at '{path}'. Run code_map first.")
        if self._is_protected(target):
            return ModuleResult.fail(
                f"{path} is on my protected list — I won't rewrite my own safety rails. "
                "Edit it yourself, or change self_improve.protected in config.yaml."
            )
        original = await run_blocking(target.read_text, "utf-8", "replace")
        if len(original.encode("utf-8")) > self.max_file_bytes:
            return ModuleResult.fail(f"{path} is too large for me to rewrite safely.")

        prompt = (
            "You are editing your own source code. Below is the complete current content of "
            f"{path} from the JARVIS project.\n\nCHANGE REQUESTED: {instruction}\n\n"
            "Rules:\n"
            "1. Return the COMPLETE new file, nothing else, in one ```python block.\n"
            "2. Keep the existing style: full type hints, docstrings, no TODOs, "
            "async where it already is async, and never let exceptions escape a tool.\n"
            "3. Keep the leading '# /path' comment.\n"
            "4. Change as little as possible — do not reformat unrelated code.\n"
            "5. Do not remove safety checks, confirmations or error handling.\n\n"
            f"CURRENT FILE:\n```python\n{original}\n```"
        )
        raw = await self.llm.complete(prompt, temperature=0.15, max_tokens=4000)
        updated = self._extract_python(raw, require_class=False) or ""
        if not updated:
            return ModuleResult.fail("The model didn't return usable code. Try being specific.")
        if updated.strip() == original.strip():
            return ModuleResult.ok("The model decided no change was needed, sir.")

        problem = self._validate_edit(original, updated, target)
        if problem:
            return ModuleResult.fail(f"I rejected my own patch: {problem}")

        diff = self._diff(original, updated, path)
        backup = await run_blocking(self._backup_file, target)
        await run_blocking(target.write_text, updated, "utf-8")

        test_summary = "skipped"
        if run_tests and self.run_tests:
            tests = await self.run_self_tests()
            test_summary = truncate(tests.output.splitlines()[0] if tests.output else "", 160)
            if not tests.success:
                await run_blocking(target.write_text, original, "utf-8")
                self._record("edit_reverted", path, instruction, backup=backup,
                             tests="failed")
                return ModuleResult(
                    success=False,
                    output=(
                        f"I wrote the change to {path}, the test suite failed, so I put it "
                        f"back exactly as it was.\n\nWhat the tests said:\n"
                        f"{truncate(tests.output, 900)}"
                    ),
                    speak="The change broke my tests, sir, so I reverted it.",
                    error="tests failed",
                    data={"diff": diff, "backup": backup},
                )

        reload_note = ""
        if self.auto_reload:
            reloaded = await self.reload_module(name=self._module_name_for(path))
            reload_note = reloaded.output

        commit = await self._git_commit([str(target)], f"self: {truncate(instruction, 60)}")
        change_id = self._record("edit", path, instruction, backup=backup,
                                 tests=test_summary, committed=commit)

        return ModuleResult(
            success=True,
            output=(
                f"Rewrote {path} (change #{change_id}).\n"
                f"  tests  : {test_summary}\n"
                f"  reload : {reload_note or 'not attempted'}\n"
                f"  backup : {backup}\n"
                f"  commit : {commit or 'not committed'}\n\n{truncate(diff, 2500)}"
            ),
            speak=f"Done, sir. {path} has been updated and the tests still pass.",
            data={"path": path, "diff": diff, "backup": backup, "change_id": change_id},
        )

    def _validate_edit(self, original: str, updated: str, target: Path) -> str:
        """Sanity-check a self-edit. Returns an error string, or ``""``."""
        try:
            ast.parse(updated)
        except SyntaxError as exc:
            return f"the new version doesn't parse (line {exc.lineno}: {exc.msg})"
        if len(updated) < len(original) * 0.5:
            return "the rewrite dropped more than half the file"
        if len(updated.encode("utf-8")) > self.max_file_bytes:
            return "the rewrite is implausibly large"
        for marker in ("TODO", "FIXME", "..."):
            if marker in updated and marker not in original:
                return f"the rewrite contains a placeholder ({marker})"
        if target.name.endswith(".py"):
            original_tools = original.count("@tool(")
            if updated.count("@tool(") < original_tools:
                return "the rewrite removes existing tools"
        for guard in ("security", "confirm", "dangerous"):
            if original.count(guard) > updated.count(guard) + 2:
                return f"the rewrite strips '{guard}' checks"
        return ""

    @staticmethod
    def _diff(before: str, after: str, path: str) -> str:
        """Unified diff between two versions of a file."""
        return "".join(
            difflib.unified_diff(
                before.splitlines(keepends=True),
                after.splitlines(keepends=True),
                fromfile=f"a/{path}",
                tofile=f"b/{path}",
                n=2,
            )
        ) or "(no textual difference)"

    @staticmethod
    def _module_name_for(path: str) -> str:
        """Map a file path to a loadable module name (``modules/x.py`` → ``x``)."""
        parts = Path(path).with_suffix("").parts
        return parts[-1] if parts else ""

    @tool(
        description="Run JARVIS's own test suite and report the result.",
        params={},
        keywords=["run your tests", "test yourself", "are you still working",
                  "check yourself", "self test"],
    )
    async def run_self_tests(self) -> ModuleResult:
        """Execute the configured test command in a subprocess."""
        command_path = self.root / self.test_command
        if not command_path.exists():
            return ModuleResult.fail(f"No test suite at {self.test_command}.")

        def _run() -> Tuple[int, str]:
            try:
                completed = subprocess.run(
                    [sys.executable, str(command_path)],
                    cwd=str(self.root),
                    capture_output=True,
                    text=True,
                    timeout=self.test_timeout,
                )
                return completed.returncode, (completed.stdout + completed.stderr)
            except subprocess.TimeoutExpired:
                return 1, f"tests timed out after {self.test_timeout:.0f}s"
            except Exception as exc:
                return 1, str(exc)

        started = time.time()
        code, output = await run_blocking(_run)
        elapsed = time.time() - started
        summary = ""
        for line in reversed(output.splitlines()):
            if "passed" in line and "failed" in line:
                summary = line.strip()
                break
        failures = [line.strip() for line in output.splitlines() if "FAILED" in line][:8]
        headline = summary or ("tests passed" if code == 0 else "tests failed")
        body = f"{headline} in {elapsed:.1f}s"
        if failures:
            body += "\n" + "\n".join(f"  {line}" for line in failures)
        return ModuleResult(
            success=code == 0,
            output=body if code == 0 else f"{body}\n\n{truncate(output[-2000:], 2000)}",
            speak=headline,
            error="" if code == 0 else "test suite failed",
            data={"exit_code": code, "seconds": round(elapsed, 1)},
        )

    @tool(
        description="Hot-reload a module or plugin after its code changed.",
        params={"name": {"type": "string", "description": "Module or plugin name",
                         "default": ""}},
        keywords=["reload yourself", "reload the module", "apply the change now",
                  "refresh your code"],
    )
    async def reload_module(self, name: str = "") -> ModuleResult:
        """Re-import a module and swap the live instance for a fresh one."""
        skill = (name or "").strip()
        if not skill:
            return ModuleResult.ok("Nothing to reload, sir.")
        if self.brain is None or not hasattr(self.brain, "reload_module"):
            return ModuleResult.ok(f"'{skill}' will be active after a restart.")
        try:
            ok, detail = await self.brain.reload_module(skill)
        except Exception as exc:
            return ModuleResult.ok(f"Reload of '{skill}' failed ({exc}); restart to apply.")
        return ModuleResult.ok(
            f"Reloaded '{skill}' — {detail}" if ok
            else f"'{skill}' needs a restart to take effect ({detail})."
        )

    @tool(
        description="Undo a previous self-modification from its backup.",
        params={
            "change_id": {"type": "integer", "description": "Change id (0 = the latest)",
                          "default": 0},
        },
        dangerous=True,
        keywords=["undo your change", "roll back", "revert yourself", "restore the backup",
                  "put it back"],
    )
    async def rollback(self, change_id: int = 0) -> ModuleResult:
        """Restore the file saved before a recorded change."""

        def _fetch() -> Optional[sqlite3.Row]:
            with self._connect() as connection:
                if change_id:
                    return connection.execute(
                        "SELECT * FROM self_changes WHERE id = ?", (int(change_id),)
                    ).fetchone()
                return connection.execute(
                    "SELECT * FROM self_changes WHERE backup != '' AND reverted = 0"
                    " ORDER BY id DESC LIMIT 1"
                ).fetchone()

        row = await run_blocking(_fetch)
        if row is None:
            return ModuleResult.fail("I have no recorded change to undo.")
        backup = Path(row["backup"] or "")
        if not backup.exists():
            return ModuleResult.fail(f"The backup for change #{row['id']} is gone.")

        target = self._resolve_source(row["target"])
        if target is None:
            target = self.plugins_dir / f"{row['target']}.py"
        try:
            await run_blocking(shutil.copy2, backup, target)
        except Exception as exc:
            return ModuleResult.fail(f"Restore failed: {exc}")

        def _mark() -> None:
            with self._connect() as connection:
                connection.execute(
                    "UPDATE self_changes SET reverted = 1 WHERE id = ?", (int(row["id"]),)
                )

        await run_blocking(_mark)
        commit = await self._git_commit([str(target)], f"self: revert change #{row['id']}")
        reload_note = ""
        if self.auto_reload:
            reloaded = await self.reload_module(name=self._module_name_for(row["target"]))
            reload_note = f" {reloaded.output}"
        return ModuleResult.ok(
            f"Reverted change #{row['id']} ({row['kind']} on {row['target']}) from "
            f"{backup.name}.{reload_note}" + (f" Committed as {commit}." if commit else "")
        )

    @tool(
        description="Show the history of JARVIS's self-modifications.",
        params={"limit": {"type": "integer", "description": "How many entries",
                          "default": 10}},
        keywords=["change history", "what have you changed", "your edit history",
                  "what did you do to yourself"],
    )
    async def change_history(self, limit: int = 10) -> ModuleResult:
        """List recorded self-changes, newest first."""

        def _rows() -> List[Dict[str, Any]]:
            try:
                with self._connect() as connection:
                    return [
                        dict(row)
                        for row in connection.execute(
                            "SELECT * FROM self_changes ORDER BY id DESC LIMIT ?",
                            (max(1, min(int(limit or 10), 50)),),
                        ).fetchall()
                    ]
            except Exception:
                return []

        rows = await run_blocking(_rows)
        if not rows:
            return ModuleResult.ok("I haven't modified myself yet, sir.", changes=[])
        listing = "\n".join(
            f"  #{row['id']} {row['created_at'][:16]} {row['kind']:<14} {row['target']}"
            + (f" · {truncate(row['description'], 60)}" if row["description"] else "")
            + (f" · {row['committed']}" if row["committed"] else "")
            + ("  [reverted]" if row["reverted"] else "")
            for row in rows
        )
        return ModuleResult(
            success=True,
            output=f"My last {len(rows)} change(s):\n{listing}",
            data={"changes": rows},
        )

    @tool(
        description="Suggest concrete improvements JARVIS could make to himself.",
        params={"focus": {"type": "string", "description": "Optional area to focus on",
                          "default": ""}},
        keywords=["how could you improve", "what should you add", "suggest improvements",
                  "what are you missing"],
    )
    async def suggest_improvements(self, focus: str = "") -> ModuleResult:
        """Have the LLM propose upgrades, grounded in the real code map."""
        overview = await self.code_map()
        if not overview.success:
            return overview
        files = overview.data.get("files", [])
        inventory = "\n".join(
            f"{row['path']}: {row['lines']} lines, {row['tools']} tools" for row in files
        )
        if self.llm is None or not getattr(self.llm, "available", False):
            return ModuleResult.ok(
                "Without the language model I can only show you the map:\n" + inventory
            )
        answer = await self.llm.complete(
            "You are JARVIS, a local Python assistant, reviewing your own codebase. "
            "Suggest five concrete, implementable improvements — each naming the exact "
            "file to change and the tool or behaviour to add. Prefer things that need no "
            "paid service. Be specific and brief.\n"
            + (f"Focus on: {focus}\n" if focus else "")
            + f"\nCODEBASE:\n{inventory}",
            temperature=0.5,
            max_tokens=700,
        )
        body = answer.strip() or inventory
        return ModuleResult(
            success=True,
            output=body,
            speak=truncate(body, 500),
            data={"files": len(files)},
        )

    @tool(
        description="Report what the self-improvement subsystem is allowed to do.",
        params={},
        keywords=["can you change yourself", "self improve status", "are you allowed to"],
    )
    async def self_status(self) -> ModuleResult:
        """Show permissions, paths and counts."""
        plugins = len(list(self.plugins_dir.glob("*.py"))) if self.plugins_dir.exists() else 0
        clones = len([p for p in self.repos_dir.iterdir() if p.is_dir()]) \
            if self.repos_dir.exists() else 0

        def _count() -> int:
            try:
                with self._connect() as connection:
                    return int(
                        connection.execute("SELECT COUNT(*) FROM self_changes").fetchone()[0]
                    )
            except Exception:
                return 0

        changes = await run_blocking(_count)
        token = "set" if os.environ.get(self.token_env) else "not set (anonymous limits)"
        lines = [
            f"Self-improvement: {'enabled' if self.enabled else 'disabled'}",
            f"  edit own code   : {self.allow_code_edit}",
            f"  install plugins : {self.allow_plugin_install}",
            f"  pip install     : {self.allow_pip_install}",
            f"  tests after edit: {self.run_tests} ({self.test_command})",
            f"  git commit      : {self.git_commit_enabled} · hot reload: {self.auto_reload}",
            f"  protected       : {', '.join(self.protected)}",
            f"  plugins         : {plugins} adapter(s) in {self.plugins_dir}",
            f"  clones          : {clones} repo(s) in {self.repos_dir}",
            f"  changes logged  : {changes} · backups in {self.backup_dir}",
            f"  ${self.token_env}: {token}",
        ]
        return ModuleResult(
            success=True,
            output="\n".join(lines),
            data={"plugins": plugins, "clones": clones, "changes": changes},
        )


# ---------------------------------------------------------------------------
# Plugin loading (used by the brain at start-up and by integrate_repo)
# ---------------------------------------------------------------------------


def load_plugin(
    path: Path, config: Any, llm: Any = None, security: Any = None
) -> Optional[BaseModule]:
    """Import a plugin file and instantiate the first ``BaseModule`` subclass.

    Args:
        path: Path to a ``plugins/*.py`` file.
        config: The global configuration object.
        llm: Optional LLM client handed to the module.
        security: Optional security guard handed to the module.

    Returns:
        The instantiated module, or ``None`` when the file defines no module.
    """
    module_name = f"jarvis_plugin_{path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        return None
    imported = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = imported
    spec.loader.exec_module(imported)

    for attribute in vars(imported).values():
        if (
            isinstance(attribute, type)
            and issubclass(attribute, BaseModule)
            and attribute is not BaseModule
            and attribute.__module__ == module_name
        ):
            return attribute(config, llm=llm, security=security)
    return None


def discover_plugins(directory: Path) -> List[Path]:
    """List loadable plugin files in ``directory``.

    Args:
        directory: The plugins folder.

    Returns:
        Sorted paths of candidate plugin modules.
    """
    if not directory.exists():
        return []
    return sorted(
        path
        for path in directory.glob("*.py")
        if not path.name.startswith("_") and path.name != "base.py"
    )


__all__ = ["SelfImprove", "load_plugin", "discover_plugins"]
